-- Disposable metadata-only fixture fragment. NEVER execute against a shared database.
-- Column names follow PKG_ECAS43/70_ATTACHMENTS and TRG_ADS_SUPPORT_DOCUMENT1;
-- absent standalone source DDL means these fixture sizes/nullability are not authoritative.
CREATE TABLE ADS_SUPPORT_DOCUMENT (ECAS_ID NUMBER(12), DOCUMENT_ID NUMBER(12) PRIMARY KEY,
 APPRAISAL_DOCUMENT_TYPE_CODE VARCHAR2(10), TRANSMISSION_TYPE_CODE VARCHAR2(1), ECAS_SUBMITTED_FILE_ID NUMBER(12),
 DOCUMENT_DESCRIPTION VARCHAR2(2000), ZIP_FILE_IND VARCHAR2(1), REVISION_COUNT NUMBER,
 ENTRY_TIMESTAMP DATE, UPDATE_TIMESTAMP DATE);
CREATE TABLE APPRAISAL_DOCUMENT_TYPE_CODE (APPRAISAL_DOCUMENT_TYPE_CODE VARCHAR2(10) PRIMARY KEY,
 DESCRIPTION VARCHAR2(200), EFFECTIVE_DATE DATE, EXPIRY_DATE DATE);
CREATE TABLE APPRAISAL_ATTACHMENT_XREF (APPRAISAL_METHOD_CODE VARCHAR2(1), APPRAISAL_DOCUMENT_TYPE_CODE VARCHAR2(10),
 DISPLAY_ORDER NUMBER, LICENSEE_ACCESS_IND VARCHAR2(1), RPF_ACCESS_IND VARCHAR2(1), BCTS_ACCESS_IND VARCHAR2(1),
 DISTRICT_ACCESS_IND VARCHAR2(1), REGION_ACCESS_IND VARCHAR2(1), HEADQUARTERS_ACCESS_IND VARCHAR2(1));
-- Shared with audit metadata: merge this definition once, never create a binary-content table.
CREATE TABLE ECAS_SUBMITTED_FILE (ECAS_ID NUMBER(12), ECAS_SUBMITTED_FILE_ID NUMBER(12) PRIMARY KEY, FILE_NAME VARCHAR2(1000));
