-- Disposable mirror of existing audit objects only; not an application/schema migration.
-- Audit package/JDBC projections establish columns; shared column constraints remain unverified.
CREATE TABLE ECAS_ACTION_CODE (ECAS_ACTION_CODE VARCHAR2(4), DESCRIPTION VARCHAR2(200));
CREATE TABLE ECAS_AUDIT_COMMENT (ECAS_ID NUMBER(12), AUDIT_EVENT_ID NUMBER(12), AUDIT_COMMENT CLOB);
CREATE TABLE ECAS_AUDIT_DETAIL (AUDIT_DETAIL_ID NUMBER(12), AUDIT_EVENT_ID NUMBER(12), ECAS_ID NUMBER(12),
 ENTRY_USERID VARCHAR2(30), ENTRY_TIMESTAMP DATE, BUSINESS_IDENTIFIER VARCHAR2(4000),
 TABLE_NAME VARCHAR2(128), COLUMN_NAME VARCHAR2(128), OLD_VALUE VARCHAR2(4000), NEW_VALUE VARCHAR2(4000));
