-- Disposable synthetic test schema only. This is not a migration or a copy of THE.
-- Intentionally includes only columns used by the read adapters. No application DML/procedures.
CREATE TABLE ORG_UNIT (ORG_UNIT_NO NUMBER PRIMARY KEY, ORG_UNIT_CODE VARCHAR2(10), ORG_UNIT_NAME VARCHAR2(100), ROLLUP_REGION_NO NUMBER, ROLLUP_DIST_NO NUMBER, EFFECTIVE_DATE DATE, EXPIRY_DATE DATE);
CREATE TABLE APPRAISAL_METHOD_CODE (APPRAISAL_METHOD_CODE VARCHAR2(3), DESCRIPTION VARCHAR2(100), EFFECTIVE_DATE DATE, EXPIRY_DATE DATE, UPDATE_TIMESTAMP TIMESTAMP);
CREATE TABLE APPRAISAL_STATUS_CODE (APPRAISAL_STATUS_CODE VARCHAR2(3), DESCRIPTION VARCHAR2(100), EFFECTIVE_DATE DATE, EXPIRY_DATE DATE, UPDATE_TIMESTAMP TIMESTAMP);
CREATE TABLE RATE_ADJUSTMENT_TYPE_CODE (RATE_ADJUSTMENT_TYPE_CODE VARCHAR2(3), DESCRIPTION VARCHAR2(100), EFFECTIVE_DATE DATE, EXPIRY_DATE DATE, UPDATE_TIMESTAMP TIMESTAMP);
CREATE TABLE NON_APPRAISED_STATUS_CODE (NON_APPRAISED_STATUS_CODE VARCHAR2(3), DESCRIPTION VARCHAR2(100), EFFECTIVE_DATE DATE, EXPIRY_DATE DATE);
CREATE TABLE APPRAISAL_CATEGORY_CODE (APPRAISAL_CATEGORY_CODE VARCHAR2(3), DESCRIPTION VARCHAR2(100), EFFECTIVE_DATE DATE, EXPIRY_DATE DATE);
CREATE TABLE REAPPRAISAL_REASON_CODE (REAPPRAISAL_REASON_CODE VARCHAR2(3), DESCRIPTION VARCHAR2(100), EFFECTIVE_DATE DATE, EXPIRY_DATE DATE);
CREATE TABLE APPRAISAL_DATA_SUBMISSION (
 ECAS_ID NUMBER(12) PRIMARY KEY, CLIENT_NUMBER VARCHAR2(8), CLIENT_LOCN_CODE VARCHAR2(2), ADMIN_DISTRICT NUMBER,
 FOREST_FILE_ID VARCHAR2(10), APPRAISAL_STATUS_CODE VARCHAR2(3), APPRAISAL_CATEGORY_CODE VARCHAR2(3),
 APPRAISAL_EFFECTIVE_DATE DATE, APPRAISAL_EXPIRY_DATE DATE, RATE_CALC_METHOD_CODE VARCHAR2(3), TOA_ELIGIBLE_IND VARCHAR2(1),
 STATUS_CHANGE_DATE DATE, RPF_SUBMITTED_DATE DATE, DISTRICT_RECEIVED_DATE DATE, SENT_DATE DATE, UPDATE_TIMESTAMP DATE,
 ENTRY_TIMESTAMP DATE, REVISION_COUNT NUMBER, CERTIFIED_FLAG VARCHAR2(1), REAPPRAISAL_REASON_CODE VARCHAR2(3),
 RPF_USER_ID VARCHAR2(30), SENT_BY_USER_ID VARCHAR2(30), TRANSFER_BY_USER_ID VARCHAR2(30), ENTRY_USERID VARCHAR2(30),
 FTAS_DATA_VALIDATED_IND VARCHAR2(1), CUTTING_PERMIT_ID VARCHAR2(10), TSB_NUMBER_CODE VARCHAR2(4), REFERENCE_MARK VARCHAR2(6),
 NET_MERCHANTABLE_AREA NUMBER, INITIAL_MERCHANTABLE_AREA NUMBER, POINT_OF_APPRAISAL_DISTANCE NUMBER,
 ADS_LOCATION_DISTANCE_AVERAGE NUMBER, POINT_OF_APPRAISAL_CODE VARCHAR2(5), APPRAISAL_SELL_PRICE_ZONE_CODE VARCHAR2(5),
 COMPARATIVE_CRUISE_IND VARCHAR2(1), SALVAGE_IND VARCHAR2(1),
 CONIF_STAND_RATE_ELIG_CODE VARCHAR2(1), DECID_STAND_RATE_ELIG_CODE VARCHAR2(1)
);
CREATE TABLE APPRAISAL_DATA_SUBMISSION_CTRL (ECAS_ID NUMBER(12), APPRAISAL_METHOD_CODE VARCHAR2(1), CLIENT_NUMBER VARCHAR2(8));
CREATE TABLE ADS_ASSIGNED_TO_USER (ECAS_ID NUMBER(12), USER_ID VARCHAR2(30));
CREATE TABLE ADS_SUBMITTED_TIMBER_MARK (ECAS_ID NUMBER(12), TIMBER_MARK VARCHAR2(6), PRIMARY_MARK_IND VARCHAR2(1), MARK_CRUISE_VOLUME NUMBER, REVISION_COUNT NUMBER);
CREATE TABLE APPRAISED_WORKSHEET (APPRAISED_WORKSHEET_ID NUMBER(12) PRIMARY KEY, ECAS_ID NUMBER(12), WORKSHEET_REFERENCE_TYPE_CODE VARCHAR2(3), CEASE_ADJUSTMENT_DATE DATE);
CREATE TABLE APPRAISED_STUMPAGE_RATE (APPRAISED_STUMPAGE_RATE_ID NUMBER(12) PRIMARY KEY, APPRAISED_WORKSHEET_ID NUMBER(12), HISTORIC_APPRAISED_WRKSHEET_ID NUMBER(12), STUMPAGE_RATE_EFFECTIVE_DATE DATE, TOTAL_STUMPAGE_RATE_AMOUNT NUMBER(6,2));
CREATE TABLE HISTORIC_APPRAISED_WORKSHEET (
 HISTORIC_APPRAISED_WRKSHEET_ID NUMBER(12) PRIMARY KEY, TIMBER_MARK VARCHAR2(6), APPRAISAL_METHOD_CODE VARCHAR2(1),
 APPRAISAL_EFFECTIVE_DATE DATE, EXPIRY_DATE DATE, APPRAISAL_STATUS_CODE VARCHAR2(3), RATE_CALC_METHOD_CODE VARCHAR2(3),
 TOTAL_OBLIGATION_ADJUSTMNT_IND VARCHAR2(1), ADJUST_QUARTERLY_IND VARCHAR2(1), CEASE_ADJUSTMENT_DATE DATE, ACTIVE_IND VARCHAR2(1), POLICY_VERSION VARCHAR2(20)
);
CREATE TABLE NON_APPRAISED_WORKSHEET (
 NON_APPRAISED_WORKSHEET_ID NUMBER(12) PRIMARY KEY, TIMBER_MARK VARCHAR2(6), APPRAISAL_METHOD_CODE VARCHAR2(1), EFFECTIVE_DATE DATE,
 EXPIRY_DATE DATE, NON_APPRAISED_STATUS_CODE VARCHAR2(3), WORKSHEET_REFERENCE_TYPE_CODE VARCHAR2(3), SDM_DECLARATION_ACCEPTANCE_DT DATE,
 TSB_NUMBER_CODE VARCHAR2(4), APPRAISAL_FOREST_ZONE_CODE VARCHAR2(5), NON_APPRAISED_RATE_TYPE_CODE VARCHAR2(3), RATE_ADJUSTMENT_TYPE_CODE VARCHAR2(3)
);
CREATE TABLE NON_APPRAISED_STUMPAGE_RATE (
 NON_APPRAISED_STUMPAGE_RATE_ID NUMBER(12) PRIMARY KEY, APPRAISED_WORKSHEET_ID NUMBER(12), HISTORIC_APPRAISED_WRKSHEET_ID NUMBER(12), NON_APPRAISED_WORKSHEET_ID NUMBER(12),
 SCALE_SPECIES_CODE VARCHAR2(10), SCALE_PRODUCT_CODE VARCHAR2(2), SCALE_GRADE_CODE VARCHAR2(1), RESERVE_STUMPAGE_RATE NUMBER(5,2),
 BONUS_BID_AMOUNT NUMBER(5,2), DEVELOPMENT_LEVY NUMBER(5,2), SILVICULTURE_LEVY NUMBER(5,2)
);
CREATE TABLE HAULING_AUTHORITY (TIMBER_MARK VARCHAR2(6), FOREST_FILE_ID VARCHAR2(10));
CREATE TABLE HARVESTING_AUTHORITY (HVA_SKEY NUMBER PRIMARY KEY, FOREST_FILE_ID VARCHAR2(10), CUTTING_PERMIT_ID VARCHAR2(10), FOREST_DISTRICT NUMBER, GEOGRAPHIC_DISTRICT NUMBER, HARVEST_AUTH_STATUS_CODE VARCHAR2(3), EXPIRY_DATE DATE, EXTEND_DATE DATE, MGMT_UNIT_ID VARCHAR2(4), MGMT_UNIT_TYPE_CODE VARCHAR2(1));
CREATE TABLE HARVESTING_HAULING_XREF (TIMBER_MARK VARCHAR2(6), HVA_SKEY NUMBER, PRIMARY_MARK_IND VARCHAR2(1));
CREATE TABLE BLANKET_ROAD_MARK (TIMBER_MARK VARCHAR2(6), FOREST_FILE_ID VARCHAR2(10), FOREST_DISTRICT NUMBER);
CREATE TABLE PRIVATE_MARK_CERTIFICATE (TIMBER_MARK VARCHAR2(6), FOREST_FILE_ID VARCHAR2(10), FOREST_DISTRICT NUMBER, PRIVATE_MARK_STATUS_CODE VARCHAR2(3), PRIVATE_MARK_EXPIRY_DATE DATE, PRIVATE_MARK_EXTEND_DATE DATE);
CREATE TABLE FOREST_FILE_CLIENT (FOREST_FILE_ID VARCHAR2(10), CLIENT_NUMBER VARCHAR2(8), FOREST_FILE_CLIENT_TYPE_CODE VARCHAR2(1));
CREATE TABLE FOREST_CLIENT (CLIENT_NUMBER VARCHAR2(8), CLIENT_NAME VARCHAR2(100));
CREATE TABLE V_CLIENT_PUBLIC (CLIENT_NUMBER VARCHAR2(8), LEGAL_FIRST_NAME VARCHAR2(100), CLIENT_NAME VARCHAR2(100));
CREATE TABLE PROV_FOREST_USE (FOREST_FILE_ID VARCHAR2(10), FILE_TYPE_CODE VARCHAR2(3), FILE_STATUS_ST VARCHAR2(3), FOREST_REGION NUMBER, SB_FUNDED_IND VARCHAR2(1), MGMT_UNIT_TYPE VARCHAR2(1), MGMT_UNIT_ID VARCHAR2(4));
CREATE TABLE TENURE_FILE_STATUS_CODE (TENURE_FILE_STATUS_CODE VARCHAR2(3), DESCRIPTION VARCHAR2(100));
CREATE TABLE HARVEST_AUTH_STATUS_CODE (HARVEST_AUTH_STATUS_CODE VARCHAR2(3));
CREATE TABLE PRIVATE_MARK_STATUS_CODE (PRIVATE_MARK_STATUS_CODE VARCHAR2(3));
CREATE TABLE FILE_TYPE_CODE (FILE_TYPE_CODE VARCHAR2(3), DESCRIPTION VARCHAR2(100), EFFECTIVE_DATE DATE, EXPIRY_DATE DATE);
CREATE TABLE ECAS_AUDIT_EVENT (ECAS_ID NUMBER(12), ECAS_ACTION_CODE VARCHAR2(4), ENTRY_TIMESTAMP DATE, ENTRY_USERID VARCHAR2(30), AUDIT_EVENT_ID NUMBER(12), SENT_TO_USERID VARCHAR2(30), ECAS_SUBMITTED_FILE_ID NUMBER(12));
CREATE TABLE ADS_SPECIES_VOLUME (ECAS_ID NUMBER(12), SPECIES_VOLUME NUMBER);
CREATE TABLE ADS_CUTTING_AUTHORITY_DETAIL (ECAS_ID NUMBER(12), ADS_LOCATION_CODE VARCHAR2(5));
CREATE TABLE INT_POINT_OF_APPRAISAL_CODE (POINT_OF_APPRAISAL_CODE VARCHAR2(5), DESCRIPTION VARCHAR2(100));
CREATE TABLE POINT_OF_APPRAISAL (POINT_OF_APPRAISAL_CODE VARCHAR2(5), APPRAISAL_ZONE NUMBER(5), EFFECTIVE_DATE DATE, APPROVED_IND VARCHAR2(1));
CREATE TABLE TSA_NUMBER_CODE (TSA_NUMBER VARCHAR2(2), DESCRIPTION VARCHAR2(100));
CREATE TABLE TSB_NUMBER_CODE (TSB_NUMBER_CODE VARCHAR2(4), DESCRIPTION VARCHAR2(100), EFFECTIVE_DATE DATE, EXPIRY_DATE DATE);
CREATE TABLE NON_APPRAISED_WS_RATE_ADDON (NON_APPRAISED_WORKSHEET_ID NUMBER(12), NON_APPRAISED_RATE_ADDON_CODE VARCHAR2(10), PRIMARY KEY (NON_APPRAISED_WORKSHEET_ID, NON_APPRAISED_RATE_ADDON_CODE));
CREATE TABLE NON_APPRAISED_RATE_ADDON_CODE (NON_APPRAISED_RATE_ADDON_CODE VARCHAR2(10) PRIMARY KEY, DESCRIPTION VARCHAR2(120), EFFECTIVE_DATE DATE, EXPIRY_DATE DATE, UPDATE_TIMESTAMP DATE);
CREATE TABLE HISTORIC_SPECIES (
 HISTORIC_SPECIES_ID NUMBER(12) PRIMARY KEY, HISTORIC_APPRAISED_WRKSHEET_ID NUMBER(12), SCALE_SPECIES_CODE VARCHAR2(10), SELLING_PRICE_ZONE VARCHAR2(2),
 SPECIES_VOLUME NUMBER(7), LUMBER_RECOVERY_FACTOR NUMBER(3), SPECIES_DECAY_PERCENT NUMBER(3), SPECIES_STUD_PERCENT NUMBER(3), SPECIES_BURN_PERCENT NUMBER(3)
);
CREATE TABLE HISTORIC_COAST_SPECIES_GRADE (
 HISTORIC_COAST_SPECIES_GRD_ID NUMBER(12) PRIMARY KEY, HISTORIC_APPRAISED_WRKSHEET_ID NUMBER(12),
 SCALE_SPECIES_CODE VARCHAR2(10), SCALE_PRODUCT_CODE VARCHAR2(2), SCALE_GRADE_CODE VARCHAR2(1), SPECIES_GRADE_PERCENT NUMBER(3)
);

CREATE TABLE STAND_RATE_ELIGIBILITY_CODE (STAND_RATE_ELIGIBILITY_CODE VARCHAR2(1) PRIMARY KEY, DESCRIPTION VARCHAR2(100));
CREATE TABLE WORKSHEET_REFERENCE_TYPE_CODE (WORKSHEET_REFERENCE_TYPE_CODE VARCHAR2(3), DESCRIPTION VARCHAR2(120), EFFECTIVE_DATE DATE, EXPIRY_DATE DATE);
CREATE TABLE APPRAISAL_FOREST_ZONE_CODE (APPRAISAL_FOREST_ZONE_CODE VARCHAR2(5), DESCRIPTION VARCHAR2(120), EFFECTIVE_DATE DATE, EXPIRY_DATE DATE);
CREATE TABLE NON_APPRAISED_RATE_TYPE_CODE (NON_APPRAISED_RATE_TYPE_CODE VARCHAR2(3), DESCRIPTION VARCHAR2(120), EFFECTIVE_DATE DATE, EXPIRY_DATE DATE);
CREATE TABLE SCALE_SPECIES_CODE (SCALE_SPECIES_CODE VARCHAR2(10), DESCRIPTION VARCHAR2(120), EFFECTIVE_DATE DATE, EXPIRY_DATE DATE);
CREATE TABLE SCALE_PRODUCT_CODE (SCALE_PRODUCT_CODE VARCHAR2(2), DESCRIPTION VARCHAR2(120), EFFECTIVE_DATE DATE, EXPIRY_DATE DATE);
CREATE TABLE SCALE_GRADE_CODE (SCALE_GRADE_CODE VARCHAR2(1), DESCRIPTION VARCHAR2(120), EFFECTIVE_DATE DATE, EXPIRY_DATE DATE);

CREATE TABLE GAS_TRANSACTION (
 GAS_TRANSACTION_ID NUMBER(12) PRIMARY KEY, TRANSACTION_COMMENT VARCHAR2(500),
 ENTRY_TIMESTAMP DATE, ENTRY_USERID VARCHAR2(30), UPDATE_TIMESTAMP DATE, UPDATE_USERID VARCHAR2(30)
);
CREATE TABLE NON_APPRAISED_WORKSHEET_AUD (
 NON_APPRAISED_WORKSHEET_AUD_ID NUMBER(12) PRIMARY KEY, NON_APPRAISED_WORKSHEET_ID NUMBER(12), GAS_TRANSACTION_ID NUMBER(12),
 TIMBER_MARK VARCHAR2(6), EFFECTIVE_DATE DATE, EXPIRY_DATE DATE, APPRAISAL_METHOD_CODE VARCHAR2(1), NON_APPRAISED_STATUS_CODE VARCHAR2(3),
 WORKSHEET_REFERENCE_TYPE_CODE VARCHAR2(3), SDM_DECLARATION_ACCEPTANCE_DT DATE, TSB_NUMBER_CODE VARCHAR2(4),
 APPRAISAL_FOREST_ZONE_CODE VARCHAR2(5), RATE_ADJUSTMENT_TYPE_CODE VARCHAR2(3), NON_APPRAISED_RATE_TYPE_CODE VARCHAR2(5),
 ENTRY_USERID VARCHAR2(30), ENTRY_TIMESTAMP DATE, UPDATE_USERID VARCHAR2(30), UPDATE_TIMESTAMP DATE
);
CREATE TABLE NON_APPRAISED_STUMPAGE_RTE_AUD (
 NON_APPRAISED_STMPG_RTE_AUD_ID NUMBER(12) PRIMARY KEY, NON_APPRAISED_STUMPAGE_RATE_ID NUMBER(12), GAS_TRANSACTION_ID NUMBER(12),
 SCALE_SPECIES_CODE VARCHAR2(10), SCALE_PRODUCT_CODE VARCHAR2(2), SCALE_GRADE_CODE VARCHAR2(1),
 BONUS_BID_AMOUNT NUMBER(5,2), DEVELOPMENT_LEVY NUMBER(5,2), SILVICULTURE_LEVY NUMBER(5,2), RESERVE_STUMPAGE_RATE NUMBER(5,2),
 LICENSEE_NOTICE_DELIVERY_IND VARCHAR2(1), ARCHIVE_NOTICE_DELIVERY_IND VARCHAR2(1), NOTICE_CREATE_DATE DATE,
 APPRAISED_WORKSHEET_ID NUMBER(12), NON_APPRAISED_WORKSHEET_ID NUMBER(12), HISTORIC_APPRAISED_WRKSHEET_ID NUMBER(12),
 ENTRY_TIMESTAMP DATE, ENTRY_USERID VARCHAR2(30), UPDATE_TIMESTAMP DATE, UPDATE_USERID VARCHAR2(30)
);
