package ca.bc.gov.nrs.taps.read.oracle;

/**
 * Ownership for ECAS-linked appraised worksheets: the submission's client and district, with region
 * from ORG_UNIT. Provisional until checked against the real schema; kept in one place for that reason.
 */
final class AppraisedScopeSql {
  private AppraisedScopeSql() {}

  static final String SOURCE = """
      SELECT AW.APPRAISED_WORKSHEET_ID AS WORKSHEET_ID,
             ADS.ECAS_ID,
             ADS.CLIENT_NUMBER,
             DISTRICT.ORG_UNIT_CODE AS ADMIN_DISTRICT_CODE,
             REGION.ORG_UNIT_CODE AS ROLLUP_REGION_CODE,
             ADS.FOREST_FILE_ID AS LICENSE,
             ADSC.APPRAISAL_METHOD_CODE,
             ADS.APPRAISAL_STATUS_CODE AS STATUS_CODE,
             STATUS_LOOKUP.DESCRIPTION AS STATUS_DESCRIPTION,
             ADS.APPRAISAL_EFFECTIVE_DATE AS EFFECTIVE_DATE,
             ADS.APPRAISAL_EXPIRY_DATE AS EXPIRY_DATE,
             ADS.RATE_CALC_METHOD_CODE,
             NVL(ADS.TOA_ELIGIBLE_IND, 'N') AS TOA_ELIGIBLE_IND,
             AW.WORKSHEET_REFERENCE_TYPE_CODE AS REFERENCE_TYPE,
             AW.CEASE_ADJUSTMENT_DATE
        FROM APPRAISED_WORKSHEET AW
        JOIN APPRAISAL_DATA_SUBMISSION ADS ON ADS.ECAS_ID = AW.ECAS_ID
        JOIN APPRAISAL_DATA_SUBMISSION_CTRL ADSC ON ADSC.ECAS_ID = ADS.ECAS_ID
        LEFT JOIN ORG_UNIT DISTRICT ON DISTRICT.ORG_UNIT_NO = ADS.ADMIN_DISTRICT
        LEFT JOIN ORG_UNIT REGION ON REGION.ORG_UNIT_NO = DISTRICT.ROLLUP_REGION_NO
        LEFT JOIN APPRAISAL_STATUS_CODE STATUS_LOOKUP
          ON STATUS_LOOKUP.APPRAISAL_STATUS_CODE = ADS.APPRAISAL_STATUS_CODE
         AND SYSDATE BETWEEN STATUS_LOOKUP.EFFECTIVE_DATE AND STATUS_LOOKUP.EXPIRY_DATE
      """;
}
