package ca.bc.gov.nrs.taps.read.oracle;

/** Main appraised History uses AWA/ASRA snapshots, scoped through the worksheet's current ADS. */
final class AppraisedGasAuditSql {
  private AppraisedGasAuditSql() {}

  static String select(ReadScopePredicate scope) {
    return """
        WITH record_scope AS (
        %s
        ), scoped_parent AS (
          SELECT WORKSHEET_ID FROM record_scope WHERE WORKSHEET_ID = ? AND %s
        ), worksheet_snapshots AS (
          SELECT AWA.*,
                 LAG(AWA.APPRAISED_WORKSHEET_AUD_ID) OVER (PARTITION BY AWA.APPRAISED_WORKSHEET_ID ORDER BY AWA.UPDATE_TIMESTAMP, AWA.APPRAISED_WORKSHEET_AUD_ID) AS PREVIOUS_ID,
                 LAG(AWA.DISCOUNT_PERCENT) OVER (PARTITION BY AWA.APPRAISED_WORKSHEET_ID ORDER BY AWA.UPDATE_TIMESTAMP, AWA.APPRAISED_WORKSHEET_AUD_ID) AS PREV_DISCOUNT_PERCENT,
                 LAG(AWA.CEASE_ADJUSTMENT_DATE) OVER (PARTITION BY AWA.APPRAISED_WORKSHEET_ID ORDER BY AWA.UPDATE_TIMESTAMP, AWA.APPRAISED_WORKSHEET_AUD_ID) AS PREV_CEASE_DATE,
                 LAG(AWA.SDM_DECLARATION_ACCEPTANCE_DT) OVER (PARTITION BY AWA.APPRAISED_WORKSHEET_ID ORDER BY AWA.UPDATE_TIMESTAMP, AWA.APPRAISED_WORKSHEET_AUD_ID) AS PREV_SDM_DATE,
                 LAG(AWA.SILVICULTURE_COST_OVERRIDE) OVER (PARTITION BY AWA.APPRAISED_WORKSHEET_ID ORDER BY AWA.UPDATE_TIMESTAMP, AWA.APPRAISED_WORKSHEET_AUD_ID) AS PREV_SILVICULTURE_COST,
                 LAG(AWA.LOGGING_COST_OVERRIDE) OVER (PARTITION BY AWA.APPRAISED_WORKSHEET_ID ORDER BY AWA.UPDATE_TIMESTAMP, AWA.APPRAISED_WORKSHEET_AUD_ID) AS PREV_LOGGING_COST,
                 LAG(AWA.MANUFACTURING_COST_OVERRIDE) OVER (PARTITION BY AWA.APPRAISED_WORKSHEET_ID ORDER BY AWA.UPDATE_TIMESTAMP, AWA.APPRAISED_WORKSHEET_AUD_ID) AS PREV_MANUFACTURING_COST
            FROM APPRAISED_WORKSHEET_AUD AWA
           WHERE EXISTS (SELECT 1 FROM scoped_parent P WHERE P.WORKSHEET_ID = AWA.APPRAISED_WORKSHEET_ID)
        ), worksheet_attributes AS (
          SELECT 1 AS ATTRIBUTE_ORDINAL, 'Discount Percent' AS ATTRIBUTE FROM DUAL
          UNION ALL SELECT 2 AS ATTRIBUTE_ORDINAL, 'Cease Adjustment Date' AS ATTRIBUTE FROM DUAL
          UNION ALL SELECT 3 AS ATTRIBUTE_ORDINAL, 'SDM Declaration Acceptance Date' AS ATTRIBUTE FROM DUAL
          UNION ALL SELECT 4 AS ATTRIBUTE_ORDINAL, 'Silviculture Cost Override' AS ATTRIBUTE FROM DUAL
          UNION ALL SELECT 5 AS ATTRIBUTE_ORDINAL, 'Logging Cost Override' AS ATTRIBUTE FROM DUAL
          UNION ALL SELECT 6 AS ATTRIBUTE_ORDINAL, 'Manufacturing Cost Override' AS ATTRIBUTE FROM DUAL
        ), rate_snapshots AS (
          SELECT ASRA.*,
                 LAG(ASRA.APPRAISED_STUMPAGE_RATE_AUD_ID) OVER (PARTITION BY ASRA.APPRAISED_STUMPAGE_RATE_ID ORDER BY ASRA.UPDATE_TIMESTAMP, ASRA.APPRAISED_STUMPAGE_RATE_AUD_ID) AS PREVIOUS_ID,
                 LAG(ASRA.STUMPAGE_RATE_EFFECTIVE_DATE) OVER (PARTITION BY ASRA.APPRAISED_STUMPAGE_RATE_ID ORDER BY ASRA.UPDATE_TIMESTAMP, ASRA.APPRAISED_STUMPAGE_RATE_AUD_ID) AS PREV_EFFECTIVE_DATE,
                 LAG(ASRA.TOTAL_STUMPAGE_RATE_AMOUNT) OVER (PARTITION BY ASRA.APPRAISED_STUMPAGE_RATE_ID ORDER BY ASRA.UPDATE_TIMESTAMP, ASRA.APPRAISED_STUMPAGE_RATE_AUD_ID) AS PREV_TOTAL_RATE,
                 LAG(ASRA.STUMPAGE_RATE_OVERRIDE_IND) OVER (PARTITION BY ASRA.APPRAISED_STUMPAGE_RATE_ID ORDER BY ASRA.UPDATE_TIMESTAMP, ASRA.APPRAISED_STUMPAGE_RATE_AUD_ID) AS PREV_OVERRIDE_IND,
                 LAG(ASRA.UPSET_STUMPAGE_RATE_OVERRIDE) OVER (PARTITION BY ASRA.APPRAISED_STUMPAGE_RATE_ID ORDER BY ASRA.UPDATE_TIMESTAMP, ASRA.APPRAISED_STUMPAGE_RATE_AUD_ID) AS PREV_UPSET_OVERRIDE,
                 LAG(ASRA.LICENSEE_NOTICE_DELIVERY_IND) OVER (PARTITION BY ASRA.APPRAISED_STUMPAGE_RATE_ID ORDER BY ASRA.UPDATE_TIMESTAMP, ASRA.APPRAISED_STUMPAGE_RATE_AUD_ID) AS PREV_LICENSEE_NOTICE,
                 LAG(ASRA.ARCHIVE_NOTICE_DELIVERY_IND) OVER (PARTITION BY ASRA.APPRAISED_STUMPAGE_RATE_ID ORDER BY ASRA.UPDATE_TIMESTAMP, ASRA.APPRAISED_STUMPAGE_RATE_AUD_ID) AS PREV_ARCHIVE_NOTICE,
                 LAG(ASRA.NOTICE_CREATE_DATE) OVER (PARTITION BY ASRA.APPRAISED_STUMPAGE_RATE_ID ORDER BY ASRA.UPDATE_TIMESTAMP, ASRA.APPRAISED_STUMPAGE_RATE_AUD_ID) AS PREV_NOTICE_DATE,
                 LAG(ASRA.ADJUSTMENT_NOTICE_MESSAGE) OVER (PARTITION BY ASRA.APPRAISED_STUMPAGE_RATE_ID ORDER BY ASRA.UPDATE_TIMESTAMP, ASRA.APPRAISED_STUMPAGE_RATE_AUD_ID) AS PREV_ADJUSTMENT_MESSAGE
            FROM APPRAISED_STUMPAGE_RATE_AUD ASRA
           WHERE EXISTS (SELECT 1 FROM scoped_parent P WHERE P.WORKSHEET_ID = ASRA.APPRAISED_WORKSHEET_ID)
             AND ASRA.HISTORIC_APPRAISED_WRKSHEET_ID IS NULL
        ), rate_attributes AS (
          SELECT 1 AS ATTRIBUTE_ORDINAL, 'Stumpage Rate Effective Date' AS ATTRIBUTE FROM DUAL
          UNION ALL SELECT 2 AS ATTRIBUTE_ORDINAL, 'Total Stumpage Rate' AS ATTRIBUTE FROM DUAL
          UNION ALL SELECT 3 AS ATTRIBUTE_ORDINAL, 'Stumpage Rate Overridden' AS ATTRIBUTE FROM DUAL
          UNION ALL SELECT 4 AS ATTRIBUTE_ORDINAL, 'Upset Stumpage Rate Override' AS ATTRIBUTE FROM DUAL
          UNION ALL SELECT 5 AS ATTRIBUTE_ORDINAL, 'Licensee Notice Delivered' AS ATTRIBUTE FROM DUAL
          UNION ALL SELECT 6 AS ATTRIBUTE_ORDINAL, 'Archive Notice Delivered' AS ATTRIBUTE FROM DUAL
          UNION ALL SELECT 7 AS ATTRIBUTE_ORDINAL, 'Notice Create Date' AS ATTRIBUTE FROM DUAL
          UNION ALL SELECT 8 AS ATTRIBUTE_ORDINAL, 'Adjustment Notice Message' AS ATTRIBUTE FROM DUAL
        ), changed_fields AS (
        SELECT 1 AS SOURCE_ORDER, AWA.APPRAISED_WORKSHEET_AUD_ID AS SNAPSHOT_ID,
               AWA.APPRAISED_WORKSHEET_ID AS WORKSHEET_ID, CAST(NULL AS NUMBER(12)) AS RATE_ID,
               AWA.GAS_TRANSACTION_ID, AWA.UPDATE_USERID AS USER_ID, AWA.UPDATE_TIMESTAMP AS EVENT_DATE,
               F.ATTRIBUTE_ORDINAL, F.ATTRIBUTE,
               CASE F.ATTRIBUTE_ORDINAL
                   WHEN 1 THEN TO_CHAR(AWA.DISCOUNT_PERCENT, 'FM990D0', 'NLS_NUMERIC_CHARACTERS=''.,''')
                   WHEN 2 THEN TO_CHAR(AWA.CEASE_ADJUSTMENT_DATE, 'YYYY-MM-DD')
                   WHEN 3 THEN TO_CHAR(AWA.SDM_DECLARATION_ACCEPTANCE_DT, 'YYYY-MM-DD')
                   WHEN 4 THEN TO_CHAR(AWA.SILVICULTURE_COST_OVERRIDE, 'FM9999990', 'NLS_NUMERIC_CHARACTERS=''.,''')
                   WHEN 5 THEN TO_CHAR(AWA.LOGGING_COST_OVERRIDE, 'FM9999990', 'NLS_NUMERIC_CHARACTERS=''.,''')
                   WHEN 6 THEN TO_CHAR(AWA.MANUFACTURING_COST_OVERRIDE, 'FM9999990', 'NLS_NUMERIC_CHARACTERS=''.,''')
               END AS CHANGED_VALUE
          FROM worksheet_snapshots AWA
         CROSS JOIN worksheet_attributes F
         WHERE AWA.PREVIOUS_ID IS NOT NULL
           AND CASE F.ATTRIBUTE_ORDINAL
                   WHEN 1 THEN DECODE(AWA.DISCOUNT_PERCENT, AWA.PREV_DISCOUNT_PERCENT, 0, 1)
                   WHEN 2 THEN DECODE(AWA.CEASE_ADJUSTMENT_DATE, AWA.PREV_CEASE_DATE, 0, 1)
                   WHEN 3 THEN DECODE(AWA.SDM_DECLARATION_ACCEPTANCE_DT, AWA.PREV_SDM_DATE, 0, 1)
                   WHEN 4 THEN DECODE(AWA.SILVICULTURE_COST_OVERRIDE, AWA.PREV_SILVICULTURE_COST, 0, 1)
                   WHEN 5 THEN DECODE(AWA.LOGGING_COST_OVERRIDE, AWA.PREV_LOGGING_COST, 0, 1)
                   WHEN 6 THEN DECODE(AWA.MANUFACTURING_COST_OVERRIDE, AWA.PREV_MANUFACTURING_COST, 0, 1)
               END = 1
        UNION ALL
        SELECT 2 AS SOURCE_ORDER, ASRA.APPRAISED_STUMPAGE_RATE_AUD_ID AS SNAPSHOT_ID,
               ASRA.APPRAISED_WORKSHEET_ID AS WORKSHEET_ID, ASRA.APPRAISED_STUMPAGE_RATE_ID AS RATE_ID,
               ASRA.GAS_TRANSACTION_ID, ASRA.UPDATE_USERID AS USER_ID, ASRA.UPDATE_TIMESTAMP AS EVENT_DATE,
               F.ATTRIBUTE_ORDINAL, F.ATTRIBUTE,
               CASE F.ATTRIBUTE_ORDINAL
                   WHEN 1 THEN TO_CHAR(ASRA.STUMPAGE_RATE_EFFECTIVE_DATE, 'YYYY-MM-DD')
                   WHEN 2 THEN TO_CHAR(ASRA.TOTAL_STUMPAGE_RATE_AMOUNT, 'FM9990D00', 'NLS_NUMERIC_CHARACTERS=''.,''')
                   WHEN 3 THEN CASE ASRA.STUMPAGE_RATE_OVERRIDE_IND WHEN 'Y' THEN 'Yes' WHEN 'N' THEN 'No' ELSE ASRA.STUMPAGE_RATE_OVERRIDE_IND END
                   WHEN 4 THEN TO_CHAR(ASRA.UPSET_STUMPAGE_RATE_OVERRIDE, 'FM9990D00', 'NLS_NUMERIC_CHARACTERS=''.,''')
                   WHEN 5 THEN CASE ASRA.LICENSEE_NOTICE_DELIVERY_IND WHEN 'Y' THEN 'Yes' WHEN 'N' THEN 'No' ELSE ASRA.LICENSEE_NOTICE_DELIVERY_IND END
                   WHEN 6 THEN CASE ASRA.ARCHIVE_NOTICE_DELIVERY_IND WHEN 'Y' THEN 'Yes' WHEN 'N' THEN 'No' ELSE ASRA.ARCHIVE_NOTICE_DELIVERY_IND END
                   WHEN 7 THEN TO_CHAR(ASRA.NOTICE_CREATE_DATE, 'YYYY-MM-DD')
                   WHEN 8 THEN ASRA.ADJUSTMENT_NOTICE_MESSAGE
               END AS CHANGED_VALUE
          FROM rate_snapshots ASRA
         CROSS JOIN rate_attributes F
         WHERE ASRA.PREVIOUS_ID IS NOT NULL
           AND CASE F.ATTRIBUTE_ORDINAL
                   WHEN 1 THEN DECODE(ASRA.STUMPAGE_RATE_EFFECTIVE_DATE, ASRA.PREV_EFFECTIVE_DATE, 0, 1)
                   WHEN 2 THEN DECODE(ASRA.TOTAL_STUMPAGE_RATE_AMOUNT, ASRA.PREV_TOTAL_RATE, 0, 1)
                   WHEN 3 THEN DECODE(ASRA.STUMPAGE_RATE_OVERRIDE_IND, ASRA.PREV_OVERRIDE_IND, 0, 1)
                   WHEN 4 THEN DECODE(ASRA.UPSET_STUMPAGE_RATE_OVERRIDE, ASRA.PREV_UPSET_OVERRIDE, 0, 1)
                   WHEN 5 THEN DECODE(ASRA.LICENSEE_NOTICE_DELIVERY_IND, ASRA.PREV_LICENSEE_NOTICE, 0, 1)
                   WHEN 6 THEN DECODE(ASRA.ARCHIVE_NOTICE_DELIVERY_IND, ASRA.PREV_ARCHIVE_NOTICE, 0, 1)
                   WHEN 7 THEN DECODE(ASRA.NOTICE_CREATE_DATE, ASRA.PREV_NOTICE_DATE, 0, 1)
                   WHEN 8 THEN DECODE(ASRA.ADJUSTMENT_NOTICE_MESSAGE, ASRA.PREV_ADJUSTMENT_MESSAGE, 0, 1)
               END = 1
        ), numbered_changes AS (
          SELECT C.*, ROW_NUMBER() OVER (
                   ORDER BY EVENT_DATE DESC, SOURCE_ORDER ASC, SNAPSHOT_ID DESC, ATTRIBUTE_ORDINAL ASC) AS RESULT_ROW
            FROM changed_fields C
        )
        SELECT (SELECT COUNT(*) FROM scoped_parent) AS PARENT_COUNT, totals.TOTAL,
               CASE WHEN C.SNAPSHOT_ID IS NOT NULL THEN
                 CASE C.SOURCE_ORDER WHEN 1 THEN 'W:' WHEN 2 THEN 'R:' END ||
                 TO_CHAR(C.SNAPSHOT_ID, 'FM999999999999') || ':' || TO_CHAR(C.ATTRIBUTE_ORDINAL, 'FM99')
               END AS EVENT_ID,
               C.WORKSHEET_ID, C.RATE_ID, C.USER_ID, C.EVENT_DATE, C.ATTRIBUTE, C.CHANGED_VALUE,
               (SELECT T.TRANSACTION_COMMENT FROM GAS_TRANSACTION T
                 WHERE T.GAS_TRANSACTION_ID = C.GAS_TRANSACTION_ID) AS COMMENT_TEXT
          FROM (SELECT COUNT(*) AS TOTAL FROM changed_fields) totals
          LEFT JOIN numbered_changes C ON C.RESULT_ROW BETWEEN ? AND ?
         ORDER BY C.RESULT_ROW
        """.formatted(AppraisedScopeSql.SOURCE, scope.sql());
  }
}
