package ca.bc.gov.nrs.taps.read.oracle;

/** SELECT version of the PKG_ECAS30/60_REF_INFO display query. */
final class EcasReferenceSql {
  private EcasReferenceSql() {}

  // Authorize on ADS ownership before joining FTAS. Conflicting FTAS rows are rejected instead of
  // taking an arbitrary first row like the legacy FETCH.
  static String select(EcasReadPredicate scope) {
    return """
        WITH record_scope AS (
          SELECT ADS.*, ADSC.APPRAISAL_METHOD_CODE, ADS.APPRAISAL_STATUS_CODE AS STATUS_CODE,
                 DISTRICT.ORG_UNIT_CODE AS ADMIN_DISTRICT_CODE,
                 DISTRICT.ORG_UNIT_NAME AS ADMIN_DISTRICT_NAME,
                 REGION.ORG_UNIT_CODE AS ROLLUP_REGION_CODE
            FROM APPRAISAL_DATA_SUBMISSION ADS
            JOIN APPRAISAL_DATA_SUBMISSION_CTRL ADSC ON ADSC.ECAS_ID = ADS.ECAS_ID
            LEFT JOIN ORG_UNIT DISTRICT ON DISTRICT.ORG_UNIT_NO = ADS.ADMIN_DISTRICT
            LEFT JOIN ORG_UNIT REGION ON REGION.ORG_UNIT_NO = DISTRICT.ROLLUP_REGION_NO
        ), scoped_parent AS (
          SELECT * FROM record_scope
           WHERE record_scope.ECAS_ID = ? AND record_scope.APPRAISAL_METHOD_CODE = ?
             AND %s
        ), selected_mark AS (
          SELECT P.*,
                 (SELECT M.TIMBER_MARK FROM ADS_SUBMITTED_TIMBER_MARK M
                   WHERE M.ECAS_ID = P.ECAS_ID
                     AND (P.APPRAISAL_METHOD_CODE = 'I' OR M.PRIMARY_MARK_IND = 'Y'))
                   AS REFERENCE_TIMBER_MARK
            FROM scoped_parent P
        ), cp_management AS (
          SELECT DISTINCT P.ECAS_ID, HVA.MGMT_UNIT_ID, HVA.MGMT_UNIT_TYPE_CODE
            FROM selected_mark P
            JOIN HARVESTING_HAULING_XREF X
              ON X.TIMBER_MARK = P.REFERENCE_TIMBER_MARK AND X.PRIMARY_MARK_IND = 'Y'
            JOIN HARVESTING_AUTHORITY HVA ON HVA.HVA_SKEY = X.HVA_SKEY
           WHERE P.FTAS_DATA_VALIDATED_IND = 'Y'
        ), fta_values AS (
          SELECT DISTINCT P.ECAS_ID, HA.FOREST_FILE_ID, HVA.CUTTING_PERMIT_ID,
                 ADMIN.ORG_UNIT_CODE AS DISPLAY_ADMIN_CODE,
                 ADMIN.ORG_UNIT_NAME AS DISPLAY_ADMIN_NAME,
                 GEO.ORG_UNIT_CODE AS GEO_DISTRICT_CODE,
                 GEO.ORG_UNIT_NAME AS GEO_DISTRICT_NAME,
                 PFU.FILE_TYPE_CODE, FTC.DESCRIPTION AS FILE_TYPE_DESCRIPTION,
                 CASE WHEN CP.MGMT_UNIT_ID IS NOT NULL AND CP.MGMT_UNIT_TYPE_CODE IS NOT NULL
                      THEN CP.MGMT_UNIT_ID ELSE PFU.MGMT_UNIT_ID END AS MGMT_UNIT_ID,
                 CASE WHEN CP.MGMT_UNIT_ID IS NOT NULL AND CP.MGMT_UNIT_TYPE_CODE IS NOT NULL
                      THEN CP.MGMT_UNIT_TYPE_CODE ELSE PFU.MGMT_UNIT_TYPE END AS MGMT_UNIT_TYPE
            FROM selected_mark P
            JOIN HAULING_AUTHORITY HA ON HA.TIMBER_MARK = P.REFERENCE_TIMBER_MARK
            JOIN HARVESTING_HAULING_XREF X ON X.TIMBER_MARK = HA.TIMBER_MARK
            JOIN HARVESTING_AUTHORITY HVA ON HVA.HVA_SKEY = X.HVA_SKEY
            JOIN ORG_UNIT ADMIN ON ADMIN.ORG_UNIT_NO = HVA.FOREST_DISTRICT
            JOIN ORG_UNIT GEO ON GEO.ORG_UNIT_NO = HVA.GEOGRAPHIC_DISTRICT
            LEFT JOIN PROV_FOREST_USE PFU ON PFU.FOREST_FILE_ID = HA.FOREST_FILE_ID
            LEFT JOIN FILE_TYPE_CODE FTC ON FTC.FILE_TYPE_CODE = PFU.FILE_TYPE_CODE
            LEFT JOIN cp_management CP ON CP.ECAS_ID = P.ECAS_ID
           WHERE P.FTAS_DATA_VALIDATED_IND = 'Y'
        ), reference_codes AS (
          SELECT P.ECAS_ID, P.APPRAISAL_METHOD_CODE, P.REVISION_COUNT,
                 COALESCE(F.FOREST_FILE_ID, P.FOREST_FILE_ID) AS LICENCE,
                 CASE WHEN F.FOREST_FILE_ID IS NOT NULL THEN F.CUTTING_PERMIT_ID
                      ELSE P.CUTTING_PERMIT_ID END AS CUTTING_PERMIT,
                 P.CLIENT_NUMBER, P.CLIENT_LOCN_CODE,
                 (SELECT C.LEGAL_FIRST_NAME || C.CLIENT_NAME FROM V_CLIENT_PUBLIC C
                   WHERE C.CLIENT_NUMBER = P.CLIENT_NUMBER) AS LICENSEE_NAME,
                 P.APPRAISAL_STATUS_CODE AS STATUS_CODE,
                 (SELECT S.DESCRIPTION FROM APPRAISAL_STATUS_CODE S
                   WHERE S.APPRAISAL_STATUS_CODE = P.APPRAISAL_STATUS_CODE) AS STATUS_DESCRIPTION,
                 P.APPRAISAL_CATEGORY_CODE, P.REAPPRAISAL_REASON_CODE, P.RATE_CALC_METHOD_CODE,
                 P.APPRAISAL_EFFECTIVE_DATE, P.APPRAISAL_EXPIRY_DATE,
                 CASE WHEN F.FOREST_FILE_ID IS NOT NULL THEN F.DISPLAY_ADMIN_CODE
                      ELSE P.ADMIN_DISTRICT_CODE END AS DISPLAY_ADMIN_CODE,
                 CASE WHEN F.FOREST_FILE_ID IS NOT NULL THEN F.DISPLAY_ADMIN_NAME
                      ELSE P.ADMIN_DISTRICT_NAME END AS DISPLAY_ADMIN_NAME,
                 F.GEO_DISTRICT_CODE, F.GEO_DISTRICT_NAME, F.FILE_TYPE_CODE, F.FILE_TYPE_DESCRIPTION,
                 CASE WHEN F.MGMT_UNIT_TYPE = 'U' THEN F.MGMT_UNIT_ID END AS FTA_TSA_CODE,
                 CASE WHEN F.MGMT_UNIT_TYPE = 'V' THEN F.MGMT_UNIT_ID
                      ELSE P.TSB_NUMBER_CODE END AS TSB_CODE,
                 P.REFERENCE_TIMBER_MARK, P.REFERENCE_MARK,
                 CASE WHEN P.APPRAISAL_METHOD_CODE = 'C' THEN
                   (SELECT NVL(SUM(V.SPECIES_VOLUME), 0) FROM ADS_SPECIES_VOLUME V
                     WHERE V.ECAS_ID = P.ECAS_ID) END AS NET_CRUISE_VOLUME,
                 P.NET_MERCHANTABLE_AREA, P.INITIAL_MERCHANTABLE_AREA,
                 P.POINT_OF_APPRAISAL_DISTANCE, P.ADS_LOCATION_DISTANCE_AVERAGE,
                 CASE WHEN P.APPRAISAL_METHOD_CODE = 'C' THEN
                   (SELECT DISTINCT D.ADS_LOCATION_CODE FROM ADS_CUTTING_AUTHORITY_DETAIL D
                     WHERE D.ECAS_ID = P.ECAS_ID) END AS MAJOR_CENTRE_CODE,
                 P.POINT_OF_APPRAISAL_CODE,
                 CASE WHEN P.APPRAISAL_METHOD_CODE = 'I' THEN
                   (SELECT C.DESCRIPTION FROM INT_POINT_OF_APPRAISAL_CODE C
                     WHERE C.POINT_OF_APPRAISAL_CODE = P.POINT_OF_APPRAISAL_CODE) END
                   AS POINT_OF_APPRAISAL_DESCRIPTION,
                 CASE WHEN P.APPRAISAL_METHOD_CODE = 'I'
                        AND P.APPRAISAL_EFFECTIVE_DATE < DATE '2018-11-01'
                        AND P.APPRAISAL_SELL_PRICE_ZONE_CODE IS NULL
                        AND P.POINT_OF_APPRAISAL_CODE IS NOT NULL
                      THEN (SELECT TO_CHAR(Z.APPRAISAL_ZONE) FROM POINT_OF_APPRAISAL Z
                             WHERE Z.POINT_OF_APPRAISAL_CODE = P.POINT_OF_APPRAISAL_CODE
                               AND Z.EFFECTIVE_DATE =
                                 (SELECT MAX(A.EFFECTIVE_DATE) FROM POINT_OF_APPRAISAL A
                                   WHERE A.POINT_OF_APPRAISAL_CODE = P.POINT_OF_APPRAISAL_CODE
                                     AND A.APPROVED_IND = 'Y'))
                      ELSE P.APPRAISAL_SELL_PRICE_ZONE_CODE END AS SELLING_PRICE_ZONE_CODE,
                 CASE WHEN P.APPRAISAL_METHOD_CODE = 'I' THEN
                   NVL(P.COMPARATIVE_CRUISE_IND, 'N') END AS COMPARATIVE_CRUISE_IND,
                 CASE WHEN P.APPRAISAL_METHOD_CODE = 'I' THEN P.SALVAGE_IND END AS SALVAGE_IND
            FROM selected_mark P
            LEFT JOIN fta_values F ON F.ECAS_ID = P.ECAS_ID
        ), enriched_parent AS (
          SELECT P.*,
                 COALESCE(P.FTA_TSA_CODE, SUBSTR(P.TSB_CODE, 1, 2)) AS TSA_CODE,
                 (SELECT T.DESCRIPTION FROM TSA_NUMBER_CODE T
                   WHERE T.TSA_NUMBER = COALESCE(P.FTA_TSA_CODE, SUBSTR(P.TSB_CODE, 1, 2)))
                   AS TSA_DESCRIPTION,
                 (SELECT T.DESCRIPTION FROM TSB_NUMBER_CODE T
                   WHERE T.TSB_NUMBER_CODE = P.TSB_CODE) AS TSB_DESCRIPTION
            FROM reference_codes P
        )
        SELECT 0 AS ROW_KIND, P.*, CAST(NULL AS VARCHAR2(6)) AS TIMBER_MARK,
               CAST(NULL AS NUMBER) AS MARK_CRUISE_VOLUME,
               CAST(NULL AS VARCHAR2(1)) AS PRIMARY_MARK_IND,
               CAST(NULL AS NUMBER) AS MARK_REVISION_COUNT
          FROM enriched_parent P
        UNION ALL
        SELECT 1, P.*, M.TIMBER_MARK, M.MARK_CRUISE_VOLUME, M.PRIMARY_MARK_IND, M.REVISION_COUNT
          FROM enriched_parent P
          JOIN ADS_SUBMITTED_TIMBER_MARK M ON M.ECAS_ID = P.ECAS_ID
         ORDER BY ROW_KIND, TIMBER_MARK
        """.formatted(scope.sql());
  }
}
