package ca.bc.gov.nrs.taps.read.oracle;

/** Raw NEW-state snapshots compared within their own worksheet/rate, before display formatting. */
final class GasAuditSql {
  private GasAuditSql() {}

  static String select(ReadScopePredicate scope) {
    return """
        WITH record_scope AS (
        %s
        ), scoped_parent AS (
          SELECT WORKSHEET_ID FROM record_scope WHERE WORKSHEET_ID = ? AND %s
        ), worksheet_snapshots AS (
          SELECT A.*,
                 LAG(A.NON_APPRAISED_WORKSHEET_AUD_ID) OVER (PARTITION BY A.NON_APPRAISED_WORKSHEET_ID ORDER BY A.UPDATE_TIMESTAMP, A.NON_APPRAISED_WORKSHEET_AUD_ID) AS PREVIOUS_ID,
                 LAG(A.TIMBER_MARK) OVER (PARTITION BY A.NON_APPRAISED_WORKSHEET_ID ORDER BY A.UPDATE_TIMESTAMP, A.NON_APPRAISED_WORKSHEET_AUD_ID) AS PREV_TIMBER_MARK,
                 LAG(A.EFFECTIVE_DATE) OVER (PARTITION BY A.NON_APPRAISED_WORKSHEET_ID ORDER BY A.UPDATE_TIMESTAMP, A.NON_APPRAISED_WORKSHEET_AUD_ID) AS PREV_EFFECTIVE_DATE,
                 LAG(A.EXPIRY_DATE) OVER (PARTITION BY A.NON_APPRAISED_WORKSHEET_ID ORDER BY A.UPDATE_TIMESTAMP, A.NON_APPRAISED_WORKSHEET_AUD_ID) AS PREV_EXPIRY_DATE,
                 LAG(A.APPRAISAL_METHOD_CODE) OVER (PARTITION BY A.NON_APPRAISED_WORKSHEET_ID ORDER BY A.UPDATE_TIMESTAMP, A.NON_APPRAISED_WORKSHEET_AUD_ID) AS PREV_APPRAISAL_METHOD_CODE,
                 LAG(A.NON_APPRAISED_STATUS_CODE) OVER (PARTITION BY A.NON_APPRAISED_WORKSHEET_ID ORDER BY A.UPDATE_TIMESTAMP, A.NON_APPRAISED_WORKSHEET_AUD_ID) AS PREV_NON_APPRAISED_STATUS_CODE,
                 LAG(A.WORKSHEET_REFERENCE_TYPE_CODE) OVER (PARTITION BY A.NON_APPRAISED_WORKSHEET_ID ORDER BY A.UPDATE_TIMESTAMP, A.NON_APPRAISED_WORKSHEET_AUD_ID) AS PREV_REFERENCE_TYPE,
                 LAG(A.TSB_NUMBER_CODE) OVER (PARTITION BY A.NON_APPRAISED_WORKSHEET_ID ORDER BY A.UPDATE_TIMESTAMP, A.NON_APPRAISED_WORKSHEET_AUD_ID) AS PREV_TSB_NUMBER_CODE,
                 LAG(A.SDM_DECLARATION_ACCEPTANCE_DT) OVER (PARTITION BY A.NON_APPRAISED_WORKSHEET_ID ORDER BY A.UPDATE_TIMESTAMP, A.NON_APPRAISED_WORKSHEET_AUD_ID) AS PREV_SDM_DATE,
                 LAG(A.APPRAISAL_FOREST_ZONE_CODE) OVER (PARTITION BY A.NON_APPRAISED_WORKSHEET_ID ORDER BY A.UPDATE_TIMESTAMP, A.NON_APPRAISED_WORKSHEET_AUD_ID) AS PREV_FOREST_ZONE,
                 LAG(A.NON_APPRAISED_RATE_TYPE_CODE) OVER (PARTITION BY A.NON_APPRAISED_WORKSHEET_ID ORDER BY A.UPDATE_TIMESTAMP, A.NON_APPRAISED_WORKSHEET_AUD_ID) AS PREV_RATE_TYPE,
                 LAG(A.RATE_ADJUSTMENT_TYPE_CODE) OVER (PARTITION BY A.NON_APPRAISED_WORKSHEET_ID ORDER BY A.UPDATE_TIMESTAMP, A.NON_APPRAISED_WORKSHEET_AUD_ID) AS PREV_RATE_ADJUSTMENT_TYPE_CODE
            FROM NON_APPRAISED_WORKSHEET_AUD A
           WHERE EXISTS (SELECT 1 FROM scoped_parent P WHERE P.WORKSHEET_ID = A.NON_APPRAISED_WORKSHEET_ID)
        ), worksheet_attributes AS (
          SELECT 1 AS ATTRIBUTE_ORDINAL, 'Timber Mark' AS ATTRIBUTE FROM DUAL
          UNION ALL SELECT 2 AS ATTRIBUTE_ORDINAL, 'Effective Date' AS ATTRIBUTE FROM DUAL
          UNION ALL SELECT 3 AS ATTRIBUTE_ORDINAL, 'Expiry Date' AS ATTRIBUTE FROM DUAL
          UNION ALL SELECT 4 AS ATTRIBUTE_ORDINAL, 'Appraisal Method' AS ATTRIBUTE FROM DUAL
          UNION ALL SELECT 5 AS ATTRIBUTE_ORDINAL, 'Non Appraised Status' AS ATTRIBUTE FROM DUAL
          UNION ALL SELECT 6 AS ATTRIBUTE_ORDINAL, 'Worksheet Reference Type' AS ATTRIBUTE FROM DUAL
          UNION ALL SELECT 7 AS ATTRIBUTE_ORDINAL, 'Timber Supply Block (TSB)' AS ATTRIBUTE FROM DUAL
          UNION ALL SELECT 8 AS ATTRIBUTE_ORDINAL, 'SDM Declaration Acceptance Date' AS ATTRIBUTE FROM DUAL
          UNION ALL SELECT 9 AS ATTRIBUTE_ORDINAL, 'Appraisal Forest Zone' AS ATTRIBUTE FROM DUAL
          UNION ALL SELECT 10 AS ATTRIBUTE_ORDINAL, 'Non Appraised Rate Type' AS ATTRIBUTE FROM DUAL
          UNION ALL SELECT 11 AS ATTRIBUTE_ORDINAL, 'Rate Adjustment Type' AS ATTRIBUTE FROM DUAL
        ), rate_snapshots AS (
          SELECT A.*,
                 LAG(A.NON_APPRAISED_STMPG_RTE_AUD_ID) OVER (PARTITION BY A.NON_APPRAISED_STUMPAGE_RATE_ID ORDER BY A.UPDATE_TIMESTAMP, A.NON_APPRAISED_STMPG_RTE_AUD_ID) AS PREVIOUS_ID,
                 LAG(A.SCALE_SPECIES_CODE) OVER (PARTITION BY A.NON_APPRAISED_STUMPAGE_RATE_ID ORDER BY A.UPDATE_TIMESTAMP, A.NON_APPRAISED_STMPG_RTE_AUD_ID) AS PREV_SCALE_SPECIES_CODE,
                 LAG(A.SCALE_PRODUCT_CODE) OVER (PARTITION BY A.NON_APPRAISED_STUMPAGE_RATE_ID ORDER BY A.UPDATE_TIMESTAMP, A.NON_APPRAISED_STMPG_RTE_AUD_ID) AS PREV_SCALE_PRODUCT_CODE,
                 LAG(A.SCALE_GRADE_CODE) OVER (PARTITION BY A.NON_APPRAISED_STUMPAGE_RATE_ID ORDER BY A.UPDATE_TIMESTAMP, A.NON_APPRAISED_STMPG_RTE_AUD_ID) AS PREV_SCALE_GRADE_CODE,
                 LAG(A.BONUS_BID_AMOUNT) OVER (PARTITION BY A.NON_APPRAISED_STUMPAGE_RATE_ID ORDER BY A.UPDATE_TIMESTAMP, A.NON_APPRAISED_STMPG_RTE_AUD_ID) AS PREV_BONUS_BID_AMOUNT,
                 LAG(A.DEVELOPMENT_LEVY) OVER (PARTITION BY A.NON_APPRAISED_STUMPAGE_RATE_ID ORDER BY A.UPDATE_TIMESTAMP, A.NON_APPRAISED_STMPG_RTE_AUD_ID) AS PREV_DEVELOPMENT_LEVY,
                 LAG(A.SILVICULTURE_LEVY) OVER (PARTITION BY A.NON_APPRAISED_STUMPAGE_RATE_ID ORDER BY A.UPDATE_TIMESTAMP, A.NON_APPRAISED_STMPG_RTE_AUD_ID) AS PREV_SILVICULTURE_LEVY,
                 LAG(A.RESERVE_STUMPAGE_RATE) OVER (PARTITION BY A.NON_APPRAISED_STUMPAGE_RATE_ID ORDER BY A.UPDATE_TIMESTAMP, A.NON_APPRAISED_STMPG_RTE_AUD_ID) AS PREV_RESERVE_STUMPAGE_RATE,
                 LAG(A.LICENSEE_NOTICE_DELIVERY_IND) OVER (PARTITION BY A.NON_APPRAISED_STUMPAGE_RATE_ID ORDER BY A.UPDATE_TIMESTAMP, A.NON_APPRAISED_STMPG_RTE_AUD_ID) AS PREV_LICENSEE_NOTICE,
                 LAG(A.ARCHIVE_NOTICE_DELIVERY_IND) OVER (PARTITION BY A.NON_APPRAISED_STUMPAGE_RATE_ID ORDER BY A.UPDATE_TIMESTAMP, A.NON_APPRAISED_STMPG_RTE_AUD_ID) AS PREV_ARCHIVE_NOTICE,
                 LAG(A.NOTICE_CREATE_DATE) OVER (PARTITION BY A.NON_APPRAISED_STUMPAGE_RATE_ID ORDER BY A.UPDATE_TIMESTAMP, A.NON_APPRAISED_STMPG_RTE_AUD_ID) AS PREV_NOTICE_CREATE_DATE
            FROM NON_APPRAISED_STUMPAGE_RTE_AUD A
           WHERE EXISTS (SELECT 1 FROM scoped_parent P WHERE P.WORKSHEET_ID = A.NON_APPRAISED_WORKSHEET_ID)
             AND A.APPRAISED_WORKSHEET_ID IS NULL AND A.HISTORIC_APPRAISED_WRKSHEET_ID IS NULL
        ), rate_attributes AS (
          SELECT 1 AS ATTRIBUTE_ORDINAL, 'Species' AS ATTRIBUTE FROM DUAL
          UNION ALL SELECT 2 AS ATTRIBUTE_ORDINAL, 'Product' AS ATTRIBUTE FROM DUAL
          UNION ALL SELECT 3 AS ATTRIBUTE_ORDINAL, 'Grade' AS ATTRIBUTE FROM DUAL
          UNION ALL SELECT 4 AS ATTRIBUTE_ORDINAL, 'Bonus Bid Amount' AS ATTRIBUTE FROM DUAL
          UNION ALL SELECT 5 AS ATTRIBUTE_ORDINAL, 'Development Levy' AS ATTRIBUTE FROM DUAL
          UNION ALL SELECT 6 AS ATTRIBUTE_ORDINAL, 'Silviculture Levy' AS ATTRIBUTE FROM DUAL
          UNION ALL SELECT 7 AS ATTRIBUTE_ORDINAL, 'Reserve Stumpage Rate' AS ATTRIBUTE FROM DUAL
          UNION ALL SELECT 8 AS ATTRIBUTE_ORDINAL, 'Licensee Notice Delivered' AS ATTRIBUTE FROM DUAL
          UNION ALL SELECT 9 AS ATTRIBUTE_ORDINAL, 'Archive Notice Delivered' AS ATTRIBUTE FROM DUAL
          UNION ALL SELECT 10 AS ATTRIBUTE_ORDINAL, 'Notice Create Date' AS ATTRIBUTE FROM DUAL
        ), changed_fields AS (
        SELECT 1 AS SOURCE_ORDER, A.NON_APPRAISED_WORKSHEET_AUD_ID AS SNAPSHOT_ID,
               A.NON_APPRAISED_WORKSHEET_ID AS WORKSHEET_ID, CAST(NULL AS NUMBER(12)) AS RATE_ID,
               A.GAS_TRANSACTION_ID, A.UPDATE_USERID AS USER_ID, A.UPDATE_TIMESTAMP AS EVENT_DATE,
               F.ATTRIBUTE_ORDINAL, F.ATTRIBUTE,
               CASE F.ATTRIBUTE_ORDINAL
                   WHEN 1 THEN A.TIMBER_MARK
                   WHEN 2 THEN TO_CHAR(A.EFFECTIVE_DATE, 'YYYY-MM-DD')
                   WHEN 3 THEN TO_CHAR(A.EXPIRY_DATE, 'YYYY-MM-DD')
                   WHEN 4 THEN A.APPRAISAL_METHOD_CODE
                   WHEN 5 THEN A.NON_APPRAISED_STATUS_CODE
                   WHEN 6 THEN A.WORKSHEET_REFERENCE_TYPE_CODE
                   WHEN 7 THEN A.TSB_NUMBER_CODE
                   WHEN 8 THEN TO_CHAR(A.SDM_DECLARATION_ACCEPTANCE_DT, 'YYYY-MM-DD')
                   WHEN 9 THEN A.APPRAISAL_FOREST_ZONE_CODE
                   WHEN 10 THEN A.NON_APPRAISED_RATE_TYPE_CODE
                   WHEN 11 THEN A.RATE_ADJUSTMENT_TYPE_CODE
               END AS CHANGED_VALUE
          FROM worksheet_snapshots A
         CROSS JOIN worksheet_attributes F
         WHERE A.PREVIOUS_ID IS NOT NULL
           AND CASE F.ATTRIBUTE_ORDINAL
                   WHEN 1 THEN DECODE(A.TIMBER_MARK, A.PREV_TIMBER_MARK, 0, 1)
                   WHEN 2 THEN DECODE(A.EFFECTIVE_DATE, A.PREV_EFFECTIVE_DATE, 0, 1)
                   WHEN 3 THEN DECODE(A.EXPIRY_DATE, A.PREV_EXPIRY_DATE, 0, 1)
                   WHEN 4 THEN DECODE(A.APPRAISAL_METHOD_CODE, A.PREV_APPRAISAL_METHOD_CODE, 0, 1)
                   WHEN 5 THEN DECODE(A.NON_APPRAISED_STATUS_CODE, A.PREV_NON_APPRAISED_STATUS_CODE, 0, 1)
                   WHEN 6 THEN DECODE(A.WORKSHEET_REFERENCE_TYPE_CODE, A.PREV_REFERENCE_TYPE, 0, 1)
                   WHEN 7 THEN DECODE(A.TSB_NUMBER_CODE, A.PREV_TSB_NUMBER_CODE, 0, 1)
                   WHEN 8 THEN DECODE(A.SDM_DECLARATION_ACCEPTANCE_DT, A.PREV_SDM_DATE, 0, 1)
                   WHEN 9 THEN DECODE(A.APPRAISAL_FOREST_ZONE_CODE, A.PREV_FOREST_ZONE, 0, 1)
                   WHEN 10 THEN DECODE(A.NON_APPRAISED_RATE_TYPE_CODE, A.PREV_RATE_TYPE, 0, 1)
                   WHEN 11 THEN DECODE(A.RATE_ADJUSTMENT_TYPE_CODE, A.PREV_RATE_ADJUSTMENT_TYPE_CODE, 0, 1)
               END = 1
        UNION ALL
        SELECT 2 AS SOURCE_ORDER, A.NON_APPRAISED_STMPG_RTE_AUD_ID AS SNAPSHOT_ID,
               A.NON_APPRAISED_WORKSHEET_ID AS WORKSHEET_ID, A.NON_APPRAISED_STUMPAGE_RATE_ID AS RATE_ID,
               A.GAS_TRANSACTION_ID, A.UPDATE_USERID AS USER_ID, A.UPDATE_TIMESTAMP AS EVENT_DATE,
               F.ATTRIBUTE_ORDINAL, F.ATTRIBUTE,
               CASE F.ATTRIBUTE_ORDINAL
                   WHEN 1 THEN A.SCALE_SPECIES_CODE
                   WHEN 2 THEN A.SCALE_PRODUCT_CODE
                   WHEN 3 THEN A.SCALE_GRADE_CODE
                   WHEN 4 THEN TO_CHAR(A.BONUS_BID_AMOUNT, 'FM990D00', 'NLS_NUMERIC_CHARACTERS=''.,''')
                   WHEN 5 THEN TO_CHAR(A.DEVELOPMENT_LEVY, 'FM990D00', 'NLS_NUMERIC_CHARACTERS=''.,''')
                   WHEN 6 THEN TO_CHAR(A.SILVICULTURE_LEVY, 'FM990D00', 'NLS_NUMERIC_CHARACTERS=''.,''')
                   WHEN 7 THEN TO_CHAR(A.RESERVE_STUMPAGE_RATE, 'FM990D00', 'NLS_NUMERIC_CHARACTERS=''.,''')
                   WHEN 8 THEN CASE A.LICENSEE_NOTICE_DELIVERY_IND WHEN 'Y' THEN 'Yes' WHEN 'N' THEN 'No' ELSE A.LICENSEE_NOTICE_DELIVERY_IND END
                   WHEN 9 THEN CASE A.ARCHIVE_NOTICE_DELIVERY_IND WHEN 'Y' THEN 'Yes' WHEN 'N' THEN 'No' ELSE A.ARCHIVE_NOTICE_DELIVERY_IND END
                   WHEN 10 THEN TO_CHAR(A.NOTICE_CREATE_DATE, 'YYYY-MM-DD')
               END AS CHANGED_VALUE
          FROM rate_snapshots A
         CROSS JOIN rate_attributes F
         WHERE A.PREVIOUS_ID IS NOT NULL
           AND CASE F.ATTRIBUTE_ORDINAL
                   WHEN 1 THEN DECODE(A.SCALE_SPECIES_CODE, A.PREV_SCALE_SPECIES_CODE, 0, 1)
                   WHEN 2 THEN DECODE(A.SCALE_PRODUCT_CODE, A.PREV_SCALE_PRODUCT_CODE, 0, 1)
                   WHEN 3 THEN DECODE(A.SCALE_GRADE_CODE, A.PREV_SCALE_GRADE_CODE, 0, 1)
                   WHEN 4 THEN DECODE(A.BONUS_BID_AMOUNT, A.PREV_BONUS_BID_AMOUNT, 0, 1)
                   WHEN 5 THEN DECODE(A.DEVELOPMENT_LEVY, A.PREV_DEVELOPMENT_LEVY, 0, 1)
                   WHEN 6 THEN DECODE(A.SILVICULTURE_LEVY, A.PREV_SILVICULTURE_LEVY, 0, 1)
                   WHEN 7 THEN DECODE(A.RESERVE_STUMPAGE_RATE, A.PREV_RESERVE_STUMPAGE_RATE, 0, 1)
                   WHEN 8 THEN DECODE(A.LICENSEE_NOTICE_DELIVERY_IND, A.PREV_LICENSEE_NOTICE, 0, 1)
                   WHEN 9 THEN DECODE(A.ARCHIVE_NOTICE_DELIVERY_IND, A.PREV_ARCHIVE_NOTICE, 0, 1)
                   WHEN 10 THEN DECODE(A.NOTICE_CREATE_DATE, A.PREV_NOTICE_CREATE_DATE, 0, 1)
               END = 1
        ), numbered_changes AS (
          SELECT C.*, ROW_NUMBER() OVER (
                   ORDER BY EVENT_DATE DESC, SOURCE_ORDER ASC, SNAPSHOT_ID DESC, ATTRIBUTE_ORDINAL ASC) AS RESULT_ROW
            FROM changed_fields C
        )
        SELECT (SELECT COUNT(*) FROM scoped_parent) AS PARENT_COUNT, totals.TOTAL,
               CASE WHEN C.SNAPSHOT_ID IS NOT NULL THEN
                 CASE C.SOURCE_ORDER WHEN 1 THEN 'W:' WHEN 2 THEN 'R:' END ||
                 TO_CHAR(C.SNAPSHOT_ID, 'FM999999999999') || ':' || TO_CHAR(C.ATTRIBUTE_ORDINAL, 'FM99')
               END AS EVENT_ID,
               C.WORKSHEET_ID, C.RATE_ID, C.USER_ID, C.EVENT_DATE, C.ATTRIBUTE, C.CHANGED_VALUE,
               (SELECT T.TRANSACTION_COMMENT FROM GAS_TRANSACTION T
                 WHERE T.GAS_TRANSACTION_ID = C.GAS_TRANSACTION_ID) AS COMMENT_TEXT
          FROM (SELECT COUNT(*) AS TOTAL FROM changed_fields) totals
          LEFT JOIN numbered_changes C ON C.RESULT_ROW BETWEEN ? AND ?
         ORDER BY C.RESULT_ROW
        """.formatted(OtherWorksheetScopeSql.NON_APPRAISED, scope.sql());
  }
}
