-- Read-only schema check for the TAPS read adapters. Run it in an already connected SQL*Plus
-- session; keep credentials and output out of Git. It only reads metadata and parses statements.
-- The table checks are generated from oracle-preflight-inventory.json by oracle-preflight.py --write.
WHENEVER OSERROR EXIT FAILURE ROLLBACK
WHENEVER SQLERROR EXIT FAILURE ROLLBACK
SET ECHO OFF
SET VERIFY OFF
SET FEEDBACK OFF
SET DEFINE OFF
SET SQLBLANKLINES ON
SET SERVEROUTPUT ON SIZE 1000000
SET LINESIZE 240
SET PAGESIZE 100

PROMPT Session details (check these, don't save them):
SELECT SYS_CONTEXT('USERENV', 'SESSION_USER') AS session_user,
       SYS_CONTEXT('USERENV', 'PROXY_USER') AS proxy_user,
       SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA') AS current_schema,
       SYS_CONTEXT('USERENV', 'AUTHENTICATION_METHOD') AS authentication_method
FROM SYS.DUAL;
SELECT SESSIONTIMEZONE AS session_timezone, DBTIMEZONE AS database_timezone,
       TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') AS database_date,
       TO_CHAR(SYSTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS TZH:TZM') AS database_timestamp,
       TO_CHAR(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS TZH:TZM') AS session_timestamp
FROM SYS.DUAL;
SELECT parameter, value FROM NLS_SESSION_PARAMETERS
WHERE parameter IN ('NLS_DATE_FORMAT', 'NLS_TIMESTAMP_FORMAT', 'NLS_DATE_LANGUAGE', 'NLS_NUMERIC_CHARACTERS')
ORDER BY parameter;

-- PREFLIGHT_BLOCK_BEGIN
DECLARE
  failures PLS_INTEGER := 0;
  checked_objects PLS_INTEGER := 0;
  checked_columns PLS_INTEGER := 0;

  PROCEDURE fail(label VARCHAR2, detail VARCHAR2) IS
  BEGIN
    failures := failures + 1;
    DBMS_OUTPUT.PUT_LINE('FAIL ' || label || ': ' || detail);
  END;

  -- Resolve local/private/public synonyms without following a database link.
  -- Effective privileges are checked separately by parsing as this session's user.
  PROCEDURE resolve_local(object_name VARCHAR2, expected_type VARCHAR2) IS
    owner_name VARCHAR2(128) := SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA');
    target_name VARCHAR2(128) := object_name;
    target_type VARCHAR2(30);
    target_status VARCHAR2(7);
    next_owner VARCHAR2(128);
    next_name VARCHAR2(128);
    link_name VARCHAR2(128);
  BEGIN
    FOR hop IN 1..16 LOOP
      BEGIN
        SELECT object_type, status INTO target_type, target_status
        FROM ALL_OBJECTS
        WHERE owner = owner_name AND object_name = target_name
          AND ((expected_type = 'RELATION' AND object_type IN ('TABLE', 'VIEW', 'MATERIALIZED VIEW'))
            OR (expected_type = 'FUNCTION' AND object_type = 'FUNCTION'))
          AND ROWNUM = 1;
        IF target_status <> 'VALID' THEN
          RAISE_APPLICATION_ERROR(-20002, 'Resolved object is not valid');
        END IF;
        DBMS_OUTPUT.PUT_LINE('RESOLVED ' || object_name || ' -> ' || owner_name || '.' || target_name || ' (' || target_type || ')');
        RETURN;
      EXCEPTION WHEN NO_DATA_FOUND THEN NULL;
      END;
      BEGIN
        SELECT table_owner, table_name, db_link INTO next_owner, next_name, link_name
        FROM ALL_SYNONYMS WHERE owner = owner_name AND synonym_name = target_name;
      EXCEPTION WHEN NO_DATA_FOUND THEN
        IF hop = 1 THEN
          SELECT table_owner, table_name, db_link INTO next_owner, next_name, link_name
          FROM ALL_SYNONYMS WHERE owner = 'PUBLIC' AND synonym_name = target_name;
        ELSE
          RAISE_APPLICATION_ERROR(-20003, 'Unresolved local synonym target');
        END IF;
      END;
      IF link_name IS NOT NULL THEN
        RAISE_APPLICATION_ERROR(-20004, 'Database-link resolution requires a separate approved review');
      END IF;
      owner_name := next_owner;
      target_name := next_name;
    END LOOP;
    RAISE_APPLICATION_ERROR(-20005, 'Synonym chain is cyclic or exceeds 16 hops');
  END;

  FUNCTION compatible(actual DBMS_SQL.DESC_REC2, expected VARCHAR2) RETURN BOOLEAN IS
  BEGIN
    IF expected = 'TEXT' THEN
      RETURN actual.col_type IN (1, 96); -- VARCHAR2/NVARCHAR2 or CHAR/NCHAR
    ELSIF expected = 'CLOB' THEN
      -- Oracle internal type 112; database-character-set CLOB, not NCLOB. Describe only.
      RETURN actual.col_type = 112 AND NVL(actual.col_charsetform, -1) = 1;
    ELSIF expected = 'NUMBER' THEN
      RETURN actual.col_type = 2;
    ELSIF expected = 'LOCAL_DATETIME' THEN
      RETURN actual.col_type IN (12, 180); -- DATE or TIMESTAMP, without timezone conversion
    ELSIF expected = 'MONEY_6_2' THEN
      RETURN actual.col_type = 2 AND NVL(actual.col_precision, -1) = 6 AND NVL(actual.col_scale, -1) = 2;
    ELSIF expected = 'MONEY_5_2' THEN
      RETURN actual.col_type = 2 AND NVL(actual.col_precision, -1) = 5 AND NVL(actual.col_scale, -1) = 2;
    END IF;
    RETURN FALSE;
  END;

  PROCEDURE check_table(object_name VARCHAR2, contract VARCHAR2) IS
    cursor_id INTEGER;
    column_count INTEGER;
    described_columns DBMS_SQL.DESC_TAB2;
    sql_text VARCHAR2(32767) := 'SELECT ';
    token VARCHAR2(256);
    expected VARCHAR2(30);
    column_name VARCHAR2(128);
    position PLS_INTEGER := 1;
    before_failures PLS_INTEGER := failures;
  BEGIN
    checked_objects := checked_objects + 1;
    resolve_local(object_name, 'RELATION');
    LOOP
      token := REGEXP_SUBSTR(contract, '[^,]+', 1, position);
      EXIT WHEN token IS NULL;
      column_name := SUBSTR(token, 1, INSTR(token, ':') - 1);
      IF position > 1 THEN sql_text := sql_text || ','; END IF;
      sql_text := sql_text || column_name;
      position := position + 1;
    END LOOP;
    sql_text := sql_text || ' FROM ' || object_name || ' WHERE 1 = 0';
    cursor_id := DBMS_SQL.OPEN_CURSOR;
    -- Parsing checks names and SELECT permission without running the query.
    DBMS_SQL.PARSE(cursor_id, sql_text, DBMS_SQL.NATIVE);
    DBMS_SQL.DESCRIBE_COLUMNS2(cursor_id, column_count, described_columns);
    IF column_count <> position - 1 THEN
      fail(object_name, 'column count differs from the query contract');
    END IF;
    FOR column_index IN 1..column_count LOOP
      token := REGEXP_SUBSTR(contract, '[^,]+', 1, column_index);
      column_name := SUBSTR(token, 1, INSTR(token, ':') - 1);
      expected := SUBSTR(token, INSTR(token, ':') + 1);
      checked_columns := checked_columns + 1;
      IF described_columns(column_index).col_name <> column_name
        OR NOT compatible(described_columns(column_index), expected) THEN
        fail(object_name || '.' || column_name, 'expected ' || expected
          || '; Oracle type=' || described_columns(column_index).col_type
          || ', precision=' || described_columns(column_index).col_precision
          || ', scale=' || described_columns(column_index).col_scale);
      END IF;
    END LOOP;
    DBMS_SQL.CLOSE_CURSOR(cursor_id);
    IF failures = before_failures THEN
      DBMS_OUTPUT.PUT_LINE('PASS SELECT_PARSE ' || object_name || ' (' || column_count || ' columns)');
    END IF;
  EXCEPTION WHEN OTHERS THEN
    IF cursor_id IS NOT NULL AND DBMS_SQL.IS_OPEN(cursor_id) THEN DBMS_SQL.CLOSE_CURSOR(cursor_id); END IF;
    fail(object_name, 'resolution/SELECT parse failed; SQLCODE=' || SQLCODE);
  END;

  PROCEDURE check_function IS
    cursor_id INTEGER;
    column_count INTEGER;
    described_columns DBMS_SQL.DESC_TAB2;
  BEGIN
    resolve_local('SIL_GET_CLIENT_NAME', 'FUNCTION');
    cursor_id := DBMS_SQL.OPEN_CURSOR;
    -- Parse only: checks the signature and EXECUTE permission without calling the function.
    DBMS_SQL.PARSE(cursor_id,
      'SELECT SIL_GET_CLIENT_NAME(CAST(NULL AS VARCHAR2(8))) AS CLIENT_NAME FROM SYS.DUAL WHERE 1 = 0',
      DBMS_SQL.NATIVE);
    DBMS_SQL.DESCRIBE_COLUMNS2(cursor_id, column_count, described_columns);
    IF column_count <> 1 OR NOT compatible(described_columns(1), 'TEXT') THEN
      fail('SIL_GET_CLIENT_NAME', 'expected a character return value');
    ELSE
      DBMS_OUTPUT.PUT_LINE('PASS FUNCTION_PARSE SIL_GET_CLIENT_NAME (body not executed)');
    END IF;
    DBMS_SQL.CLOSE_CURSOR(cursor_id);
  EXCEPTION WHEN OTHERS THEN
    IF cursor_id IS NOT NULL AND DBMS_SQL.IS_OPEN(cursor_id) THEN DBMS_SQL.CLOSE_CURSOR(cursor_id); END IF;
    fail('SIL_GET_CLIENT_NAME', 'resolution/function parse failed; SQLCODE=' || SQLCODE);
  END;
BEGIN
  -- INVENTORY_BEGIN
  -- Generated by oracle-preflight.py; do not edit these calls by hand.
  check_table('ADS_CUTTING_AUTHORITY_DETAIL',
    'ECAS_ID:NUMBER,ADS_LOCATION_CODE:TEXT');
  check_table('ADS_SPECIES_VOLUME',
    'ECAS_ID:NUMBER,SPECIES_VOLUME:NUMBER');
  check_table('ADS_SUBMITTED_TIMBER_MARK',
    'ECAS_ID:NUMBER,TIMBER_MARK:TEXT,PRIMARY_MARK_IND:TEXT,MARK_CRUISE_VOLUME:NUMBER,' ||
    'REVISION_COUNT:NUMBER');
  check_table('ADS_SUPPORT_DOCUMENT',
    'ECAS_ID:NUMBER,DOCUMENT_ID:NUMBER,APPRAISAL_DOCUMENT_TYPE_CODE:TEXT,TRANSMISSION_TYPE_CODE:TEXT,' ||
    'ECAS_SUBMITTED_FILE_ID:NUMBER,DOCUMENT_DESCRIPTION:TEXT,ZIP_FILE_IND:TEXT,REVISION_COUNT:NUMBER,' ||
    'ENTRY_TIMESTAMP:LOCAL_DATETIME,UPDATE_TIMESTAMP:LOCAL_DATETIME');
  check_table('APPRAISAL_ATTACHMENT_XREF',
    'APPRAISAL_METHOD_CODE:TEXT,APPRAISAL_DOCUMENT_TYPE_CODE:TEXT,DISPLAY_ORDER:NUMBER,LICENSEE_ACCESS_IND:TEXT,' ||
    'RPF_ACCESS_IND:TEXT,BCTS_ACCESS_IND:TEXT,DISTRICT_ACCESS_IND:TEXT,REGION_ACCESS_IND:TEXT,' ||
    'HEADQUARTERS_ACCESS_IND:TEXT');
  check_table('APPRAISAL_CATEGORY_CODE',
    'APPRAISAL_CATEGORY_CODE:TEXT,DESCRIPTION:TEXT,EFFECTIVE_DATE:LOCAL_DATETIME,EXPIRY_DATE:LOCAL_DATETIME');
  check_table('APPRAISAL_DATA_SUBMISSION',
    'ECAS_ID:NUMBER,CLIENT_NUMBER:TEXT,CLIENT_LOCN_CODE:TEXT,ADMIN_DISTRICT:NUMBER,' ||
    'FOREST_FILE_ID:TEXT,APPRAISAL_STATUS_CODE:TEXT,APPRAISAL_CATEGORY_CODE:TEXT,APPRAISAL_EFFECTIVE_DATE:LOCAL_DATETIME,' ||
    'APPRAISAL_EXPIRY_DATE:LOCAL_DATETIME,RATE_CALC_METHOD_CODE:TEXT,TOA_ELIGIBLE_IND:TEXT,STATUS_CHANGE_DATE:LOCAL_DATETIME,' ||
    'RPF_SUBMITTED_DATE:LOCAL_DATETIME,DISTRICT_RECEIVED_DATE:LOCAL_DATETIME,SENT_DATE:LOCAL_DATETIME,UPDATE_TIMESTAMP:LOCAL_DATETIME,' ||
    'ENTRY_TIMESTAMP:LOCAL_DATETIME,REVISION_COUNT:NUMBER,CERTIFIED_FLAG:TEXT,REAPPRAISAL_REASON_CODE:TEXT,' ||
    'RPF_USER_ID:TEXT,SENT_BY_USER_ID:TEXT,TRANSFER_BY_USER_ID:TEXT,ENTRY_USERID:TEXT,' ||
    'FTAS_DATA_VALIDATED_IND:TEXT,CUTTING_PERMIT_ID:TEXT,TSB_NUMBER_CODE:TEXT,REFERENCE_MARK:TEXT,' ||
    'NET_MERCHANTABLE_AREA:NUMBER,INITIAL_MERCHANTABLE_AREA:NUMBER,POINT_OF_APPRAISAL_DISTANCE:NUMBER,ADS_LOCATION_DISTANCE_AVERAGE:NUMBER,' ||
    'POINT_OF_APPRAISAL_CODE:TEXT,APPRAISAL_SELL_PRICE_ZONE_CODE:TEXT,COMPARATIVE_CRUISE_IND:TEXT,SALVAGE_IND:TEXT');
  check_table('APPRAISAL_DATA_SUBMISSION_CTRL',
    'ECAS_ID:NUMBER,APPRAISAL_METHOD_CODE:TEXT,CLIENT_NUMBER:TEXT');
  check_table('APPRAISAL_DOCUMENT_TYPE_CODE',
    'APPRAISAL_DOCUMENT_TYPE_CODE:TEXT,DESCRIPTION:TEXT,EFFECTIVE_DATE:LOCAL_DATETIME,EXPIRY_DATE:LOCAL_DATETIME');
  check_table('APPRAISAL_METHOD_CODE',
    'APPRAISAL_METHOD_CODE:TEXT,DESCRIPTION:TEXT,EFFECTIVE_DATE:LOCAL_DATETIME,EXPIRY_DATE:LOCAL_DATETIME,' ||
    'UPDATE_TIMESTAMP:LOCAL_DATETIME');
  check_table('APPRAISAL_STATUS_CODE',
    'APPRAISAL_STATUS_CODE:TEXT,DESCRIPTION:TEXT,EFFECTIVE_DATE:LOCAL_DATETIME,EXPIRY_DATE:LOCAL_DATETIME,' ||
    'UPDATE_TIMESTAMP:LOCAL_DATETIME');
  check_table('APPRAISED_STUMPAGE_RATE',
    'APPRAISED_STUMPAGE_RATE_ID:NUMBER,APPRAISED_WORKSHEET_ID:NUMBER,HISTORIC_APPRAISED_WRKSHEET_ID:NUMBER,STUMPAGE_RATE_EFFECTIVE_DATE:LOCAL_DATETIME,' ||
    'TOTAL_STUMPAGE_RATE_AMOUNT:MONEY_6_2');
  check_table('APPRAISED_WORKSHEET',
    'APPRAISED_WORKSHEET_ID:NUMBER,ECAS_ID:NUMBER,WORKSHEET_REFERENCE_TYPE_CODE:TEXT,CEASE_ADJUSTMENT_DATE:LOCAL_DATETIME');
  check_table('BLANKET_ROAD_MARK',
    'TIMBER_MARK:TEXT,FOREST_FILE_ID:TEXT,FOREST_DISTRICT:NUMBER');
  check_table('ECAS_ACTION_CODE',
    'ECAS_ACTION_CODE:TEXT,DESCRIPTION:TEXT');
  check_table('ECAS_AUDIT_COMMENT',
    'ECAS_ID:NUMBER,AUDIT_EVENT_ID:NUMBER,AUDIT_COMMENT:CLOB');
  check_table('ECAS_AUDIT_DETAIL',
    'AUDIT_DETAIL_ID:NUMBER,AUDIT_EVENT_ID:NUMBER,ECAS_ID:NUMBER,ENTRY_USERID:TEXT,' ||
    'ENTRY_TIMESTAMP:LOCAL_DATETIME,BUSINESS_IDENTIFIER:TEXT,TABLE_NAME:TEXT,COLUMN_NAME:TEXT,' ||
    'OLD_VALUE:TEXT,NEW_VALUE:TEXT');
  check_table('ECAS_AUDIT_EVENT',
    'ECAS_ID:NUMBER,ECAS_ACTION_CODE:TEXT,ENTRY_TIMESTAMP:LOCAL_DATETIME,ENTRY_USERID:TEXT,' ||
    'AUDIT_EVENT_ID:NUMBER,SENT_TO_USERID:TEXT,ECAS_SUBMITTED_FILE_ID:NUMBER');
  check_table('ECAS_SUBMITTED_FILE',
    'ECAS_ID:NUMBER,ECAS_SUBMITTED_FILE_ID:NUMBER,FILE_NAME:TEXT');
  check_table('FILE_TYPE_CODE',
    'FILE_TYPE_CODE:TEXT,DESCRIPTION:TEXT,EFFECTIVE_DATE:LOCAL_DATETIME,EXPIRY_DATE:LOCAL_DATETIME');
  check_table('FOREST_CLIENT',
    'CLIENT_NUMBER:TEXT,CLIENT_NAME:TEXT');
  check_table('FOREST_FILE_CLIENT',
    'FOREST_FILE_ID:TEXT,CLIENT_NUMBER:TEXT,FOREST_FILE_CLIENT_TYPE_CODE:TEXT');
  check_table('HARVESTING_AUTHORITY',
    'HVA_SKEY:NUMBER,FOREST_FILE_ID:TEXT,CUTTING_PERMIT_ID:TEXT,FOREST_DISTRICT:NUMBER,' ||
    'GEOGRAPHIC_DISTRICT:NUMBER,HARVEST_AUTH_STATUS_CODE:TEXT,EXPIRY_DATE:LOCAL_DATETIME,EXTEND_DATE:LOCAL_DATETIME,' ||
    'MGMT_UNIT_ID:TEXT,MGMT_UNIT_TYPE_CODE:TEXT');
  check_table('HARVESTING_HAULING_XREF',
    'TIMBER_MARK:TEXT,HVA_SKEY:NUMBER,PRIMARY_MARK_IND:TEXT');
  check_table('HARVEST_AUTH_STATUS_CODE',
    'HARVEST_AUTH_STATUS_CODE:TEXT');
  check_table('HAULING_AUTHORITY',
    'TIMBER_MARK:TEXT,FOREST_FILE_ID:TEXT');
  check_table('HISTORIC_APPRAISED_WORKSHEET',
    'HISTORIC_APPRAISED_WRKSHEET_ID:NUMBER,TIMBER_MARK:TEXT,APPRAISAL_METHOD_CODE:TEXT,APPRAISAL_EFFECTIVE_DATE:LOCAL_DATETIME,' ||
    'EXPIRY_DATE:LOCAL_DATETIME,APPRAISAL_STATUS_CODE:TEXT,RATE_CALC_METHOD_CODE:TEXT,TOTAL_OBLIGATION_ADJUSTMNT_IND:TEXT,' ||
    'ADJUST_QUARTERLY_IND:TEXT,CEASE_ADJUSTMENT_DATE:LOCAL_DATETIME,ACTIVE_IND:TEXT,POLICY_VERSION:TEXT');
  check_table('HISTORIC_COAST_SPECIES_GRADE',
    'HISTORIC_COAST_SPECIES_GRD_ID:NUMBER,HISTORIC_APPRAISED_WRKSHEET_ID:NUMBER,SCALE_SPECIES_CODE:TEXT,SCALE_PRODUCT_CODE:TEXT,' ||
    'SCALE_GRADE_CODE:TEXT,SPECIES_GRADE_PERCENT:NUMBER');
  check_table('HISTORIC_SPECIES',
    'HISTORIC_SPECIES_ID:NUMBER,HISTORIC_APPRAISED_WRKSHEET_ID:NUMBER,SCALE_SPECIES_CODE:TEXT,SELLING_PRICE_ZONE:TEXT,' ||
    'SPECIES_VOLUME:NUMBER,LUMBER_RECOVERY_FACTOR:NUMBER,SPECIES_DECAY_PERCENT:NUMBER,SPECIES_STUD_PERCENT:NUMBER,' ||
    'SPECIES_BURN_PERCENT:NUMBER');
  check_table('INT_POINT_OF_APPRAISAL_CODE',
    'POINT_OF_APPRAISAL_CODE:TEXT,DESCRIPTION:TEXT');
  check_table('NON_APPRAISED_RATE_ADDON_CODE',
    'NON_APPRAISED_RATE_ADDON_CODE:TEXT,DESCRIPTION:TEXT,EFFECTIVE_DATE:LOCAL_DATETIME,EXPIRY_DATE:LOCAL_DATETIME,' ||
    'UPDATE_TIMESTAMP:LOCAL_DATETIME');
  check_table('NON_APPRAISED_STATUS_CODE',
    'NON_APPRAISED_STATUS_CODE:TEXT,DESCRIPTION:TEXT,EFFECTIVE_DATE:LOCAL_DATETIME,EXPIRY_DATE:LOCAL_DATETIME');
  check_table('NON_APPRAISED_STUMPAGE_RATE',
    'NON_APPRAISED_STUMPAGE_RATE_ID:NUMBER,APPRAISED_WORKSHEET_ID:NUMBER,HISTORIC_APPRAISED_WRKSHEET_ID:NUMBER,NON_APPRAISED_WORKSHEET_ID:NUMBER,' ||
    'SCALE_SPECIES_CODE:TEXT,SCALE_PRODUCT_CODE:TEXT,SCALE_GRADE_CODE:TEXT,RESERVE_STUMPAGE_RATE:MONEY_5_2,' ||
    'BONUS_BID_AMOUNT:MONEY_5_2,DEVELOPMENT_LEVY:MONEY_5_2,SILVICULTURE_LEVY:MONEY_5_2');
  check_table('NON_APPRAISED_WORKSHEET',
    'NON_APPRAISED_WORKSHEET_ID:NUMBER,TIMBER_MARK:TEXT,APPRAISAL_METHOD_CODE:TEXT,EFFECTIVE_DATE:LOCAL_DATETIME,' ||
    'EXPIRY_DATE:LOCAL_DATETIME,NON_APPRAISED_STATUS_CODE:TEXT,WORKSHEET_REFERENCE_TYPE_CODE:TEXT,SDM_DECLARATION_ACCEPTANCE_DT:LOCAL_DATETIME,' ||
    'TSB_NUMBER_CODE:TEXT,APPRAISAL_FOREST_ZONE_CODE:TEXT,NON_APPRAISED_RATE_TYPE_CODE:TEXT,RATE_ADJUSTMENT_TYPE_CODE:TEXT');
  check_table('NON_APPRAISED_WS_RATE_ADDON',
    'NON_APPRAISED_WORKSHEET_ID:NUMBER,NON_APPRAISED_RATE_ADDON_CODE:TEXT');
  check_table('ORG_UNIT',
    'ORG_UNIT_NO:NUMBER,ORG_UNIT_CODE:TEXT,ORG_UNIT_NAME:TEXT,ROLLUP_REGION_NO:NUMBER,' ||
    'EFFECTIVE_DATE:LOCAL_DATETIME,EXPIRY_DATE:LOCAL_DATETIME,ROLLUP_DIST_NO:NUMBER');
  check_table('POINT_OF_APPRAISAL',
    'POINT_OF_APPRAISAL_CODE:TEXT,APPRAISAL_ZONE:NUMBER,EFFECTIVE_DATE:LOCAL_DATETIME,APPROVED_IND:TEXT');
  check_table('PRIVATE_MARK_CERTIFICATE',
    'TIMBER_MARK:TEXT,FOREST_FILE_ID:TEXT,FOREST_DISTRICT:NUMBER,PRIVATE_MARK_STATUS_CODE:TEXT,' ||
    'PRIVATE_MARK_EXPIRY_DATE:LOCAL_DATETIME,PRIVATE_MARK_EXTEND_DATE:LOCAL_DATETIME');
  check_table('PRIVATE_MARK_STATUS_CODE',
    'PRIVATE_MARK_STATUS_CODE:TEXT');
  check_table('PROV_FOREST_USE',
    'FOREST_FILE_ID:TEXT,FILE_TYPE_CODE:TEXT,FILE_STATUS_ST:TEXT,FOREST_REGION:NUMBER,' ||
    'SB_FUNDED_IND:TEXT,MGMT_UNIT_TYPE:TEXT,MGMT_UNIT_ID:TEXT');
  check_table('RATE_ADJUSTMENT_TYPE_CODE',
    'RATE_ADJUSTMENT_TYPE_CODE:TEXT,DESCRIPTION:TEXT,EFFECTIVE_DATE:LOCAL_DATETIME,EXPIRY_DATE:LOCAL_DATETIME,' ||
    'UPDATE_TIMESTAMP:LOCAL_DATETIME');
  check_table('REAPPRAISAL_REASON_CODE',
    'REAPPRAISAL_REASON_CODE:TEXT,DESCRIPTION:TEXT,EFFECTIVE_DATE:LOCAL_DATETIME,EXPIRY_DATE:LOCAL_DATETIME');
  check_table('TENURE_FILE_STATUS_CODE',
    'TENURE_FILE_STATUS_CODE:TEXT,DESCRIPTION:TEXT');
  check_table('TSA_NUMBER_CODE',
    'TSA_NUMBER:TEXT,DESCRIPTION:TEXT');
  check_table('TSB_NUMBER_CODE',
    'TSB_NUMBER_CODE:TEXT,DESCRIPTION:TEXT');
  check_table('V_CLIENT_PUBLIC',
    'CLIENT_NUMBER:TEXT,LEGAL_FIRST_NAME:TEXT,CLIENT_NAME:TEXT');
  -- INVENTORY_END
  check_function;
  DBMS_OUTPUT.PUT_LINE('PREFLIGHT SUMMARY objects=' || checked_objects || ', columns=' || checked_columns || ', failures=' || failures);
  IF failures > 0 THEN
    RAISE_APPLICATION_ERROR(-20001, 'TAPS read preflight failed; Oracle activation remains blocked');
  END IF;
  DBMS_OUTPUT.PUT_LINE('PASS TAPS read schema/parse preflight (data and function behaviour not checked)');
END;
-- PREFLIGHT_BLOCK_END
/
EXIT SUCCESS ROLLBACK
