#!/usr/bin/env python3
"""Maintain the static SQL*Plus inventory. This tool never connects to Oracle."""
import argparse
import json
from pathlib import Path
import re


def render(inventory):
    families = {"TEXT", "CLOB", "NUMBER", "LOCAL_DATETIME", "MONEY_6_2", "MONEY_5_2"}
    seen = set()
    lines = ["  -- Generated by oracle-preflight.py; do not edit these calls by hand."]
    for obj in inventory["objects"]:
        name = obj["name"]
        assert re.fullmatch(r"[A-Z][A-Z0-9_]*", name) and name not in seen
        seen.add(name)
        columns = obj["columns"]
        assert columns and len({column["name"] for column in columns}) == len(columns)
        for column in columns:
            assert re.fullmatch(r"[A-Z][A-Z0-9_]*", column["name"])
            assert column["family"] in families
            assert isinstance(column["archiveDdlVerified"], bool)
        tokens = [f'{column["name"]}:{column["family"]}' for column in columns]
        chunks = [",".join(tokens[index:index + 4]) for index in range(0, len(tokens), 4)]
        lines.append(f"  check_table('{name}',")
        for index, chunk in enumerate(chunks):
            final = index == len(chunks) - 1
            lines.append("    '" + chunk + ("');" if final else ",' ||"))
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="Regenerate inventory calls in the committed SQL pack")
    args = parser.parse_args()
    directory = Path(__file__).resolve().parent
    inventory = json.loads((directory / "oracle-preflight-inventory.json").read_text())
    path = directory / "oracle-preflight.sql"
    text = path.read_text()
    assert len(inventory["functions"]) == 1
    helper = inventory["functions"][0]
    assert helper["name"] == "SIL_GET_CLIENT_NAME" and helper["returnFamily"] == "TEXT"
    assert "'" + helper["parseOnlySql"] + "'" in text, "Function parse contract differs from SQL pack"
    prefix, rest = text.split("  -- INVENTORY_BEGIN\n", 1)
    _, suffix = rest.split("  -- INVENTORY_END\n", 1)
    expected = prefix + "  -- INVENTORY_BEGIN\n" + render(inventory) + "  -- INVENTORY_END\n" + suffix
    if args.write:
        path.write_text(expected)
    elif text != expected:
        raise SystemExit("SQL inventory is stale; run scripts/oracle-preflight.py --write")
    print(f'Preflight inventory verified: {len(inventory["objects"])} objects, '
          f'{sum(len(obj["columns"]) for obj in inventory["objects"])} columns; no database connection.')


if __name__ == "__main__":
    main()
