name: PR

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

concurrency:
  group: pr-${{ github.event.number }}
  cancel-in-progress: true

permissions: {}

jobs:
  builds:
    name: Build (${{ matrix.package }})
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-24.04
    permissions:
      attestations: write
      id-token: write
      packages: write
    strategy:
      matrix:
        package: [backend, frontend]
    steps:
      - uses: bcgov/action-builder-ghcr@cb2629351c87dd1c2130073e4ebb7233a9653a63 # v4.4.1
        with:
          package: ${{ matrix.package }}
          tags: |
            ${{ github.event.number }}
            ${{ github.event.pull_request.head.sha }}

  deploy:
    name: DEV Preview
    needs: [builds]
    if: needs.builds.result == 'success'
    permissions:
      contents: read
    uses: ./.github/workflows/reusable-deploy.yml
    secrets:
      oc_namespace: ${{ secrets.oc_namespace }}
      oc_token: ${{ secrets.oc_token }}
    with:
      environment: dev
      target: ${{ github.event.number }}
      tag: ${{ github.event.pull_request.head.sha }}

  smoke:
    name: DEV Smoke
    needs: [deploy]
    if: needs.deploy.result == 'success'
    uses: ./.github/workflows/reusable-tests.yml
    with:
      target: ${{ github.event.number }}

  results:
    name: PR Results
    needs: [builds, deploy, smoke]
    if: always()
    runs-on: ubuntu-slim
    steps:
      - name: Check all results
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: exit 1
